// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/auth"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/configs"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/groups"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/health"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/satellites"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/spire"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations/users"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/cmdutils"
)

// NewGroundControlAPI creates a new GroundControl instance
func NewGroundControlAPI(spec *loads.Document) *GroundControlAPI {
	return &GroundControlAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),
		TxtProducer:  runtime.TextProducer(),

		GroupsAddSatelliteToGroupHandler: groups.AddSatelliteToGroupHandlerFunc(func(params groups.AddSatelliteToGroupParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.AddSatelliteToGroup has not yet been implemented")
		}),

		UsersChangeOwnPasswordHandler: users.ChangeOwnPasswordHandlerFunc(func(params users.ChangeOwnPasswordParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation users.ChangeOwnPassword has not yet been implemented")
		}),

		UsersChangeUserPasswordHandler: users.ChangeUserPasswordHandlerFunc(func(params users.ChangeUserPasswordParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation users.ChangeUserPassword has not yet been implemented")
		}),

		ConfigsCreateConfigHandler: configs.CreateConfigHandlerFunc(func(params configs.CreateConfigParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation configs.CreateConfig has not yet been implemented")
		}),

		UsersCreateUserHandler: users.CreateUserHandlerFunc(func(params users.CreateUserParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation users.CreateUser has not yet been implemented")
		}),

		ConfigsDeleteConfigHandler: configs.DeleteConfigHandlerFunc(func(params configs.DeleteConfigParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation configs.DeleteConfig has not yet been implemented")
		}),

		GroupsDeleteGroupHandler: groups.DeleteGroupHandlerFunc(func(params groups.DeleteGroupParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.DeleteGroup has not yet been implemented")
		}),

		SatellitesDeleteSatelliteHandler: satellites.DeleteSatelliteHandlerFunc(func(params satellites.DeleteSatelliteParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.DeleteSatellite has not yet been implemented")
		}),

		UsersDeleteUserHandler: users.DeleteUserHandlerFunc(func(params users.DeleteUserParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation users.DeleteUser has not yet been implemented")
		}),

		SatellitesGetCachedImagesHandler: satellites.GetCachedImagesHandlerFunc(func(params satellites.GetCachedImagesParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.GetCachedImages has not yet been implemented")
		}),

		ConfigsGetConfigHandler: configs.GetConfigHandlerFunc(func(params configs.GetConfigParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation configs.GetConfig has not yet been implemented")
		}),

		GroupsGetGroupHandler: groups.GetGroupHandlerFunc(func(params groups.GetGroupParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.GetGroup has not yet been implemented")
		}),

		SatellitesGetSatelliteHandler: satellites.GetSatelliteHandlerFunc(func(params satellites.GetSatelliteParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.GetSatellite has not yet been implemented")
		}),

		SatellitesGetSatelliteStatusHandler: satellites.GetSatelliteStatusHandlerFunc(func(params satellites.GetSatelliteStatusParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.GetSatelliteStatus has not yet been implemented")
		}),

		SpireGetSpireStatusHandler: spire.GetSpireStatusHandlerFunc(func(params spire.GetSpireStatusParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation spire.GetSpireStatus has not yet been implemented")
		}),

		UsersGetUserHandler: users.GetUserHandlerFunc(func(params users.GetUserParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation users.GetUser has not yet been implemented")
		}),

		HealthHealthHandler: health.HealthHandlerFunc(func(params health.HealthParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation health.Health has not yet been implemented")
		}),

		SatellitesListActiveSatellitesHandler: satellites.ListActiveSatellitesHandlerFunc(func(params satellites.ListActiveSatellitesParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.ListActiveSatellites has not yet been implemented")
		}),

		ConfigsListConfigsHandler: configs.ListConfigsHandlerFunc(func(params configs.ListConfigsParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation configs.ListConfigs has not yet been implemented")
		}),

		GroupsListGroupSatellitesHandler: groups.ListGroupSatellitesHandlerFunc(func(params groups.ListGroupSatellitesParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.ListGroupSatellites has not yet been implemented")
		}),

		GroupsListGroupsHandler: groups.ListGroupsHandlerFunc(func(params groups.ListGroupsParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.ListGroups has not yet been implemented")
		}),

		SatellitesListSatellitesHandler: satellites.ListSatellitesHandlerFunc(func(params satellites.ListSatellitesParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.ListSatellites has not yet been implemented")
		}),

		SpireListSpireAgentsHandler: spire.ListSpireAgentsHandlerFunc(func(params spire.ListSpireAgentsParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation spire.ListSpireAgents has not yet been implemented")
		}),

		SatellitesListStaleSatellitesHandler: satellites.ListStaleSatellitesHandlerFunc(func(params satellites.ListStaleSatellitesParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.ListStaleSatellites has not yet been implemented")
		}),

		UsersListUsersHandler: users.ListUsersHandlerFunc(func(params users.ListUsersParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation users.ListUsers has not yet been implemented")
		}),

		AuthLoginHandler: auth.LoginHandlerFunc(func(params auth.LoginParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation auth.Login has not yet been implemented")
		}),

		AuthLogoutHandler: auth.LogoutHandlerFunc(func(params auth.LogoutParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation auth.Logout has not yet been implemented")
		}),

		HealthPingHandler: health.PingHandlerFunc(func(params health.PingParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation health.Ping has not yet been implemented")
		}),

		SatellitesRegisterSatelliteHandler: satellites.RegisterSatelliteHandlerFunc(func(params satellites.RegisterSatelliteParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation satellites.RegisterSatellite has not yet been implemented")
		}),

		SpireRegisterSatelliteWithSpiffeHandler: spire.RegisterSatelliteWithSpiffeHandlerFunc(func(params spire.RegisterSatelliteWithSpiffeParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation spire.RegisterSatelliteWithSpiffe has not yet been implemented")
		}),

		GroupsRemoveSatelliteFromGroupHandler: groups.RemoveSatelliteFromGroupHandlerFunc(func(params groups.RemoveSatelliteFromGroupParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.RemoveSatelliteFromGroup has not yet been implemented")
		}),

		ConfigsSetSatelliteConfigHandler: configs.SetSatelliteConfigHandlerFunc(func(params configs.SetSatelliteConfigParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation configs.SetSatelliteConfig has not yet been implemented")
		}),

		SatellitesSpiffeZtrHandler: satellites.SpiffeZtrHandlerFunc(func(params satellites.SpiffeZtrParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation satellites.SpiffeZtr has not yet been implemented")
		}),

		GroupsSyncGroupHandler: groups.SyncGroupHandlerFunc(func(params groups.SyncGroupParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation groups.SyncGroup has not yet been implemented")
		}),

		SatellitesSyncSatelliteHandler: satellites.SyncSatelliteHandlerFunc(func(params satellites.SyncSatelliteParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation satellites.SyncSatellite has not yet been implemented")
		}),

		ConfigsUpdateConfigHandler: configs.UpdateConfigHandlerFunc(func(params configs.UpdateConfigParams, principal any) middleware.Responder {
			_ = params
			_ = principal

			return middleware.NotImplemented("operation configs.UpdateConfig has not yet been implemented")
		}),

		SatellitesZtrHandler: satellites.ZtrHandlerFunc(func(params satellites.ZtrParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation satellites.Ztr has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuthAuth: func(token string) (any, error) {
			_ = token

			return nil, errors.NotImplemented("api key auth (bearerAuth) Authorization from header param [Authorization] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

// GroundControlAPI Ground Control manages Harbor Satellite registration, configuration,
// group membership, user administration, status reporting, and SPIRE/SPIFFE
// bootstrap flows.
type GroundControlAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer
	// TxtProducer registers a producer for the following mime types:
	//   - text/plain
	TxtProducer runtime.Producer

	// BearerAuthAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuthAuth func(string) (any, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// GroupsAddSatelliteToGroupHandler sets the operation handler for the add satellite to group operation
	GroupsAddSatelliteToGroupHandler groups.AddSatelliteToGroupHandler
	// UsersChangeOwnPasswordHandler sets the operation handler for the change own password operation
	UsersChangeOwnPasswordHandler users.ChangeOwnPasswordHandler
	// UsersChangeUserPasswordHandler sets the operation handler for the change user password operation
	UsersChangeUserPasswordHandler users.ChangeUserPasswordHandler
	// ConfigsCreateConfigHandler sets the operation handler for the create config operation
	ConfigsCreateConfigHandler configs.CreateConfigHandler
	// UsersCreateUserHandler sets the operation handler for the create user operation
	UsersCreateUserHandler users.CreateUserHandler
	// ConfigsDeleteConfigHandler sets the operation handler for the delete config operation
	ConfigsDeleteConfigHandler configs.DeleteConfigHandler
	// GroupsDeleteGroupHandler sets the operation handler for the delete group operation
	GroupsDeleteGroupHandler groups.DeleteGroupHandler
	// SatellitesDeleteSatelliteHandler sets the operation handler for the delete satellite operation
	SatellitesDeleteSatelliteHandler satellites.DeleteSatelliteHandler
	// UsersDeleteUserHandler sets the operation handler for the delete user operation
	UsersDeleteUserHandler users.DeleteUserHandler
	// SatellitesGetCachedImagesHandler sets the operation handler for the get cached images operation
	SatellitesGetCachedImagesHandler satellites.GetCachedImagesHandler
	// ConfigsGetConfigHandler sets the operation handler for the get config operation
	ConfigsGetConfigHandler configs.GetConfigHandler
	// GroupsGetGroupHandler sets the operation handler for the get group operation
	GroupsGetGroupHandler groups.GetGroupHandler
	// SatellitesGetSatelliteHandler sets the operation handler for the get satellite operation
	SatellitesGetSatelliteHandler satellites.GetSatelliteHandler
	// SatellitesGetSatelliteStatusHandler sets the operation handler for the get satellite status operation
	SatellitesGetSatelliteStatusHandler satellites.GetSatelliteStatusHandler
	// SpireGetSpireStatusHandler sets the operation handler for the get spire status operation
	SpireGetSpireStatusHandler spire.GetSpireStatusHandler
	// UsersGetUserHandler sets the operation handler for the get user operation
	UsersGetUserHandler users.GetUserHandler
	// HealthHealthHandler sets the operation handler for the health operation
	HealthHealthHandler health.HealthHandler
	// SatellitesListActiveSatellitesHandler sets the operation handler for the list active satellites operation
	SatellitesListActiveSatellitesHandler satellites.ListActiveSatellitesHandler
	// ConfigsListConfigsHandler sets the operation handler for the list configs operation
	ConfigsListConfigsHandler configs.ListConfigsHandler
	// GroupsListGroupSatellitesHandler sets the operation handler for the list group satellites operation
	GroupsListGroupSatellitesHandler groups.ListGroupSatellitesHandler
	// GroupsListGroupsHandler sets the operation handler for the list groups operation
	GroupsListGroupsHandler groups.ListGroupsHandler
	// SatellitesListSatellitesHandler sets the operation handler for the list satellites operation
	SatellitesListSatellitesHandler satellites.ListSatellitesHandler
	// SpireListSpireAgentsHandler sets the operation handler for the list spire agents operation
	SpireListSpireAgentsHandler spire.ListSpireAgentsHandler
	// SatellitesListStaleSatellitesHandler sets the operation handler for the list stale satellites operation
	SatellitesListStaleSatellitesHandler satellites.ListStaleSatellitesHandler
	// UsersListUsersHandler sets the operation handler for the list users operation
	UsersListUsersHandler users.ListUsersHandler
	// AuthLoginHandler sets the operation handler for the login operation
	AuthLoginHandler auth.LoginHandler
	// AuthLogoutHandler sets the operation handler for the logout operation
	AuthLogoutHandler auth.LogoutHandler
	// HealthPingHandler sets the operation handler for the ping operation
	HealthPingHandler health.PingHandler
	// SatellitesRegisterSatelliteHandler sets the operation handler for the register satellite operation
	SatellitesRegisterSatelliteHandler satellites.RegisterSatelliteHandler
	// SpireRegisterSatelliteWithSpiffeHandler sets the operation handler for the register satellite with spiffe operation
	SpireRegisterSatelliteWithSpiffeHandler spire.RegisterSatelliteWithSpiffeHandler
	// GroupsRemoveSatelliteFromGroupHandler sets the operation handler for the remove satellite from group operation
	GroupsRemoveSatelliteFromGroupHandler groups.RemoveSatelliteFromGroupHandler
	// ConfigsSetSatelliteConfigHandler sets the operation handler for the set satellite config operation
	ConfigsSetSatelliteConfigHandler configs.SetSatelliteConfigHandler
	// SatellitesSpiffeZtrHandler sets the operation handler for the spiffe ztr operation
	SatellitesSpiffeZtrHandler satellites.SpiffeZtrHandler
	// GroupsSyncGroupHandler sets the operation handler for the sync group operation
	GroupsSyncGroupHandler groups.SyncGroupHandler
	// SatellitesSyncSatelliteHandler sets the operation handler for the sync satellite operation
	SatellitesSyncSatelliteHandler satellites.SyncSatelliteHandler
	// ConfigsUpdateConfigHandler sets the operation handler for the update config operation
	ConfigsUpdateConfigHandler configs.UpdateConfigHandler
	// SatellitesZtrHandler sets the operation handler for the ztr operation
	SatellitesZtrHandler satellites.ZtrHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []cmdutils.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...any)
}

// UseRedoc for documentation at /docs
func (o *GroundControlAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *GroundControlAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *GroundControlAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *GroundControlAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *GroundControlAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *GroundControlAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *GroundControlAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *GroundControlAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *GroundControlAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the GroundControlAPI
func (o *GroundControlAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}
	if o.TxtProducer == nil {
		unregistered = append(unregistered, "TxtProducer")
	}

	if o.BearerAuthAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.GroupsAddSatelliteToGroupHandler == nil {
		unregistered = append(unregistered, "groups.AddSatelliteToGroupHandler")
	}
	if o.UsersChangeOwnPasswordHandler == nil {
		unregistered = append(unregistered, "users.ChangeOwnPasswordHandler")
	}
	if o.UsersChangeUserPasswordHandler == nil {
		unregistered = append(unregistered, "users.ChangeUserPasswordHandler")
	}
	if o.ConfigsCreateConfigHandler == nil {
		unregistered = append(unregistered, "configs.CreateConfigHandler")
	}
	if o.UsersCreateUserHandler == nil {
		unregistered = append(unregistered, "users.CreateUserHandler")
	}
	if o.ConfigsDeleteConfigHandler == nil {
		unregistered = append(unregistered, "configs.DeleteConfigHandler")
	}
	if o.GroupsDeleteGroupHandler == nil {
		unregistered = append(unregistered, "groups.DeleteGroupHandler")
	}
	if o.SatellitesDeleteSatelliteHandler == nil {
		unregistered = append(unregistered, "satellites.DeleteSatelliteHandler")
	}
	if o.UsersDeleteUserHandler == nil {
		unregistered = append(unregistered, "users.DeleteUserHandler")
	}
	if o.SatellitesGetCachedImagesHandler == nil {
		unregistered = append(unregistered, "satellites.GetCachedImagesHandler")
	}
	if o.ConfigsGetConfigHandler == nil {
		unregistered = append(unregistered, "configs.GetConfigHandler")
	}
	if o.GroupsGetGroupHandler == nil {
		unregistered = append(unregistered, "groups.GetGroupHandler")
	}
	if o.SatellitesGetSatelliteHandler == nil {
		unregistered = append(unregistered, "satellites.GetSatelliteHandler")
	}
	if o.SatellitesGetSatelliteStatusHandler == nil {
		unregistered = append(unregistered, "satellites.GetSatelliteStatusHandler")
	}
	if o.SpireGetSpireStatusHandler == nil {
		unregistered = append(unregistered, "spire.GetSpireStatusHandler")
	}
	if o.UsersGetUserHandler == nil {
		unregistered = append(unregistered, "users.GetUserHandler")
	}
	if o.HealthHealthHandler == nil {
		unregistered = append(unregistered, "health.HealthHandler")
	}
	if o.SatellitesListActiveSatellitesHandler == nil {
		unregistered = append(unregistered, "satellites.ListActiveSatellitesHandler")
	}
	if o.ConfigsListConfigsHandler == nil {
		unregistered = append(unregistered, "configs.ListConfigsHandler")
	}
	if o.GroupsListGroupSatellitesHandler == nil {
		unregistered = append(unregistered, "groups.ListGroupSatellitesHandler")
	}
	if o.GroupsListGroupsHandler == nil {
		unregistered = append(unregistered, "groups.ListGroupsHandler")
	}
	if o.SatellitesListSatellitesHandler == nil {
		unregistered = append(unregistered, "satellites.ListSatellitesHandler")
	}
	if o.SpireListSpireAgentsHandler == nil {
		unregistered = append(unregistered, "spire.ListSpireAgentsHandler")
	}
	if o.SatellitesListStaleSatellitesHandler == nil {
		unregistered = append(unregistered, "satellites.ListStaleSatellitesHandler")
	}
	if o.UsersListUsersHandler == nil {
		unregistered = append(unregistered, "users.ListUsersHandler")
	}
	if o.AuthLoginHandler == nil {
		unregistered = append(unregistered, "auth.LoginHandler")
	}
	if o.AuthLogoutHandler == nil {
		unregistered = append(unregistered, "auth.LogoutHandler")
	}
	if o.HealthPingHandler == nil {
		unregistered = append(unregistered, "health.PingHandler")
	}
	if o.SatellitesRegisterSatelliteHandler == nil {
		unregistered = append(unregistered, "satellites.RegisterSatelliteHandler")
	}
	if o.SpireRegisterSatelliteWithSpiffeHandler == nil {
		unregistered = append(unregistered, "spire.RegisterSatelliteWithSpiffeHandler")
	}
	if o.GroupsRemoveSatelliteFromGroupHandler == nil {
		unregistered = append(unregistered, "groups.RemoveSatelliteFromGroupHandler")
	}
	if o.ConfigsSetSatelliteConfigHandler == nil {
		unregistered = append(unregistered, "configs.SetSatelliteConfigHandler")
	}
	if o.SatellitesSpiffeZtrHandler == nil {
		unregistered = append(unregistered, "satellites.SpiffeZtrHandler")
	}
	if o.GroupsSyncGroupHandler == nil {
		unregistered = append(unregistered, "groups.SyncGroupHandler")
	}
	if o.SatellitesSyncSatelliteHandler == nil {
		unregistered = append(unregistered, "satellites.SyncSatelliteHandler")
	}
	if o.ConfigsUpdateConfigHandler == nil {
		unregistered = append(unregistered, "configs.UpdateConfigHandler")
	}
	if o.SatellitesZtrHandler == nil {
		unregistered = append(unregistered, "satellites.ZtrHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *GroundControlAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *GroundControlAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		if name == "bearerAuth" {
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, o.BearerAuthAuth)
		}
	}

	return result
}

// Authorizer returns the registered authorizer
func (o *GroundControlAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *GroundControlAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		if mt == "application/json" {
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}

	return result
}

// ProducersFor gets the producers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *GroundControlAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		case "text/plain":
			result["text/plain"] = o.TxtProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}

	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *GroundControlAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the ground control API
func (o *GroundControlAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *GroundControlAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/groups/satellite"] = groups.NewAddSatelliteToGroup(o.context, o.GroupsAddSatelliteToGroupHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/api/users/password"] = users.NewChangeOwnPassword(o.context, o.UsersChangeOwnPasswordHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/api/users/{username}/password"] = users.NewChangeUserPassword(o.context, o.UsersChangeUserPasswordHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/configs"] = configs.NewCreateConfig(o.context, o.ConfigsCreateConfigHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/users"] = users.NewCreateUser(o.context, o.UsersCreateUserHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/configs/{config}"] = configs.NewDeleteConfig(o.context, o.ConfigsDeleteConfigHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/groups/{group}"] = groups.NewDeleteGroup(o.context, o.GroupsDeleteGroupHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/satellites/{satellite}"] = satellites.NewDeleteSatellite(o.context, o.SatellitesDeleteSatelliteHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/users/{username}"] = users.NewDeleteUser(o.context, o.UsersDeleteUserHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/satellites/{satellite}/images"] = satellites.NewGetCachedImages(o.context, o.SatellitesGetCachedImagesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/configs/{config}"] = configs.NewGetConfig(o.context, o.ConfigsGetConfigHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/groups/{group}"] = groups.NewGetGroup(o.context, o.GroupsGetGroupHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/satellites/{satellite}"] = satellites.NewGetSatellite(o.context, o.SatellitesGetSatelliteHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/satellites/{satellite}/status"] = satellites.NewGetSatelliteStatus(o.context, o.SatellitesGetSatelliteStatusHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/spire/status"] = spire.NewGetSpireStatus(o.context, o.SpireGetSpireStatusHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/users/{username}"] = users.NewGetUser(o.context, o.UsersGetUserHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/health"] = health.NewHealth(o.context, o.HealthHealthHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/satellites/active"] = satellites.NewListActiveSatellites(o.context, o.SatellitesListActiveSatellitesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/configs"] = configs.NewListConfigs(o.context, o.ConfigsListConfigsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/groups/{group}/satellites"] = groups.NewListGroupSatellites(o.context, o.GroupsListGroupSatellitesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/groups"] = groups.NewListGroups(o.context, o.GroupsListGroupsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/satellites"] = satellites.NewListSatellites(o.context, o.SatellitesListSatellitesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/spire/agents"] = spire.NewListSpireAgents(o.context, o.SpireListSpireAgentsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/satellites/stale"] = satellites.NewListStaleSatellites(o.context, o.SatellitesListStaleSatellitesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/api/users"] = users.NewListUsers(o.context, o.UsersListUsersHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = auth.NewLogin(o.context, o.AuthLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/logout"] = auth.NewLogout(o.context, o.AuthLogoutHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/ping"] = health.NewPing(o.context, o.HealthPingHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/satellites"] = satellites.NewRegisterSatellite(o.context, o.SatellitesRegisterSatelliteHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/satellites/register"] = spire.NewRegisterSatelliteWithSpiffe(o.context, o.SpireRegisterSatelliteWithSpiffeHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/api/groups/satellite"] = groups.NewRemoveSatelliteFromGroup(o.context, o.GroupsRemoveSatelliteFromGroupHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/configs/satellite"] = configs.NewSetSatelliteConfig(o.context, o.ConfigsSetSatelliteConfigHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/satellites/spiffe-ztr"] = satellites.NewSpiffeZtr(o.context, o.SatellitesSpiffeZtrHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/api/groups/sync"] = groups.NewSyncGroup(o.context, o.GroupsSyncGroupHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/satellites/sync"] = satellites.NewSyncSatellite(o.context, o.SatellitesSyncSatelliteHandler)
	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/api/configs/{config}"] = configs.NewUpdateConfig(o.context, o.ConfigsUpdateConfigHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/satellites/ztr/{token}"] = satellites.NewZtr(o.context, o.SatellitesZtrHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *GroundControlAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *GroundControlAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *GroundControlAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *GroundControlAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *GroundControlAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
