// Code generated by go-swagger; DO NOT EDIT.

// Package server Ground Control
//
//	Ground Control manages Harbor Satellite registration, configuration,
//	group membership, user administration, status reporting, and SPIRE/SPIFFE
//	bootstrap flows.
//
//	Schemes:
//	  https
//	Host: localhost
//	BasePath: /
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//	  - text/plain
//
// swagger:meta
package server
