// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddSatelliteToGroupHandlerFunc turns a function with the right signature into a add satellite to group handler
type AddSatelliteToGroupHandlerFunc func(AddSatelliteToGroupParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn AddSatelliteToGroupHandlerFunc) Handle(params AddSatelliteToGroupParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// AddSatelliteToGroupHandler interface for that can handle valid add satellite to group params
type AddSatelliteToGroupHandler interface {
	Handle(AddSatelliteToGroupParams, any) middleware.Responder
}

// NewAddSatelliteToGroup creates a new http.Handler for the add satellite to group operation
func NewAddSatelliteToGroup(ctx *middleware.Context, handler AddSatelliteToGroupHandler) *AddSatelliteToGroup {
	return &AddSatelliteToGroup{Context: ctx, Handler: handler}
}

// AddSatelliteToGroup swagger:route POST /api/groups/satellite groups addSatelliteToGroup
//
// Adds a satellite to a group.
type AddSatelliteToGroup struct {
	Context *middleware.Context
	Handler AddSatelliteToGroupHandler
}

func (o *AddSatelliteToGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewAddSatelliteToGroupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
