// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// AddSatelliteToGroupOKCode is the HTTP code returned for type AddSatelliteToGroupOK
const AddSatelliteToGroupOKCode int = 200

// AddSatelliteToGroupOK Satellite was added to the group or was already a member.
//
// swagger:response addSatelliteToGroupOK
type AddSatelliteToGroupOK struct {

	// In: Body
	Payload *models.APIMessageResponse `json:"body,omitempty"`
}

// NewAddSatelliteToGroupOK creates AddSatelliteToGroupOK with default headers values
func NewAddSatelliteToGroupOK() *AddSatelliteToGroupOK {

	return &AddSatelliteToGroupOK{}
}

// WithPayload adds the payload to the add satellite to group o k response
func (o *AddSatelliteToGroupOK) WithPayload(payload *models.APIMessageResponse) *AddSatelliteToGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add satellite to group o k response
func (o *AddSatelliteToGroupOK) SetPayload(payload *models.APIMessageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSatelliteToGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddSatelliteToGroupBadRequestCode is the HTTP code returned for type AddSatelliteToGroupBadRequest
const AddSatelliteToGroupBadRequestCode int = 400

// AddSatelliteToGroupBadRequest Satellite or group is invalid or not found.
//
// swagger:response addSatelliteToGroupBadRequest
type AddSatelliteToGroupBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewAddSatelliteToGroupBadRequest creates AddSatelliteToGroupBadRequest with default headers values
func NewAddSatelliteToGroupBadRequest() *AddSatelliteToGroupBadRequest {

	return &AddSatelliteToGroupBadRequest{}
}

// WithPayload adds the payload to the add satellite to group bad request response
func (o *AddSatelliteToGroupBadRequest) WithPayload(payload *models.AppError) *AddSatelliteToGroupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add satellite to group bad request response
func (o *AddSatelliteToGroupBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSatelliteToGroupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddSatelliteToGroupUnauthorizedCode is the HTTP code returned for type AddSatelliteToGroupUnauthorized
const AddSatelliteToGroupUnauthorizedCode int = 401

// AddSatelliteToGroupUnauthorized Authorization token is missing or invalid.
//
// swagger:response addSatelliteToGroupUnauthorized
type AddSatelliteToGroupUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewAddSatelliteToGroupUnauthorized creates AddSatelliteToGroupUnauthorized with default headers values
func NewAddSatelliteToGroupUnauthorized() *AddSatelliteToGroupUnauthorized {

	return &AddSatelliteToGroupUnauthorized{}
}

// WithPayload adds the payload to the add satellite to group unauthorized response
func (o *AddSatelliteToGroupUnauthorized) WithPayload(payload *models.AppError) *AddSatelliteToGroupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add satellite to group unauthorized response
func (o *AddSatelliteToGroupUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSatelliteToGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddSatelliteToGroupInternalServerErrorCode is the HTTP code returned for type AddSatelliteToGroupInternalServerError
const AddSatelliteToGroupInternalServerErrorCode int = 500

// AddSatelliteToGroupInternalServerError Satellite could not be added to the group.
//
// swagger:response addSatelliteToGroupInternalServerError
type AddSatelliteToGroupInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewAddSatelliteToGroupInternalServerError creates AddSatelliteToGroupInternalServerError with default headers values
func NewAddSatelliteToGroupInternalServerError() *AddSatelliteToGroupInternalServerError {

	return &AddSatelliteToGroupInternalServerError{}
}

// WithPayload adds the payload to the add satellite to group internal server error response
func (o *AddSatelliteToGroupInternalServerError) WithPayload(payload *models.AppError) *AddSatelliteToGroupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add satellite to group internal server error response
func (o *AddSatelliteToGroupInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddSatelliteToGroupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
