// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteGroupParams creates a new DeleteGroupParams object
//
// There are no default values defined in the spec.
func NewDeleteGroupParams() DeleteGroupParams {

	return DeleteGroupParams{}
}

// DeleteGroupParams contains all the bound params for the delete group operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteGroup
type DeleteGroupParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
	// Group name.
	// Required: true
	// In: path
	Group string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteGroupParams() beforehand.
func (o *DeleteGroupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rGroup, rhkGroup, _ := route.Params.GetOK("group")
	if err := o.bindGroup(rGroup, rhkGroup, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGroup binds and validates parameter Group from path.
func (o *DeleteGroupParams) bindGroup(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Group = raw

	return nil
}
