// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteGroupHandlerFunc turns a function with the right signature into a delete group handler
type DeleteGroupHandlerFunc func(DeleteGroupParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteGroupHandlerFunc) Handle(params DeleteGroupParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// DeleteGroupHandler interface for that can handle valid delete group params
type DeleteGroupHandler interface {
	Handle(DeleteGroupParams, any) middleware.Responder
}

// NewDeleteGroup creates a new http.Handler for the delete group operation
func NewDeleteGroup(ctx *middleware.Context, handler DeleteGroupHandler) *DeleteGroup {
	return &DeleteGroup{Context: ctx, Handler: handler}
}

// DeleteGroup swagger:route DELETE /api/groups/{group} groups deleteGroup
//
// Deletes a group.
type DeleteGroup struct {
	Context *middleware.Context
	Handler DeleteGroupHandler
}

func (o *DeleteGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewDeleteGroupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
