// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// GetGroupOKCode is the HTTP code returned for type GetGroupOK
const GetGroupOKCode int = 200

// GetGroupOK Group returned.
//
// swagger:response getGroupOK
type GetGroupOK struct {

	// In: Body
	Payload *models.APIGroup `json:"body,omitempty"`
}

// NewGetGroupOK creates GetGroupOK with default headers values
func NewGetGroupOK() *GetGroupOK {

	return &GetGroupOK{}
}

// WithPayload adds the payload to the get group o k response
func (o *GetGroupOK) WithPayload(payload *models.APIGroup) *GetGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group o k response
func (o *GetGroupOK) SetPayload(payload *models.APIGroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupUnauthorizedCode is the HTTP code returned for type GetGroupUnauthorized
const GetGroupUnauthorizedCode int = 401

// GetGroupUnauthorized Authorization token is missing or invalid.
//
// swagger:response getGroupUnauthorized
type GetGroupUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetGroupUnauthorized creates GetGroupUnauthorized with default headers values
func NewGetGroupUnauthorized() *GetGroupUnauthorized {

	return &GetGroupUnauthorized{}
}

// WithPayload adds the payload to the get group unauthorized response
func (o *GetGroupUnauthorized) WithPayload(payload *models.AppError) *GetGroupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group unauthorized response
func (o *GetGroupUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupNotFoundCode is the HTTP code returned for type GetGroupNotFound
const GetGroupNotFoundCode int = 404

// GetGroupNotFound Group was not found.
//
// swagger:response getGroupNotFound
type GetGroupNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetGroupNotFound creates GetGroupNotFound with default headers values
func NewGetGroupNotFound() *GetGroupNotFound {

	return &GetGroupNotFound{}
}

// WithPayload adds the payload to the get group not found response
func (o *GetGroupNotFound) WithPayload(payload *models.AppError) *GetGroupNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group not found response
func (o *GetGroupNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGroupInternalServerErrorCode is the HTTP code returned for type GetGroupInternalServerError
const GetGroupInternalServerErrorCode int = 500

// GetGroupInternalServerError Group could not be loaded.
//
// swagger:response getGroupInternalServerError
type GetGroupInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetGroupInternalServerError creates GetGroupInternalServerError with default headers values
func NewGetGroupInternalServerError() *GetGroupInternalServerError {

	return &GetGroupInternalServerError{}
}

// WithPayload adds the payload to the get group internal server error response
func (o *GetGroupInternalServerError) WithPayload(payload *models.AppError) *GetGroupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get group internal server error response
func (o *GetGroupInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGroupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
