// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ListGroupsOKCode is the HTTP code returned for type ListGroupsOK
const ListGroupsOKCode int = 200

// ListGroupsOK Groups returned.
//
// swagger:response listGroupsOK
type ListGroupsOK struct {

	// In: Body
	Payload []*models.APIGroup `json:"body,omitempty"`
}

// NewListGroupsOK creates ListGroupsOK with default headers values
func NewListGroupsOK() *ListGroupsOK {

	return &ListGroupsOK{}
}

// WithPayload adds the payload to the list groups o k response
func (o *ListGroupsOK) WithPayload(payload []*models.APIGroup) *ListGroupsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups o k response
func (o *ListGroupsOK) SetPayload(payload []*models.APIGroup) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.APIGroup, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListGroupsUnauthorizedCode is the HTTP code returned for type ListGroupsUnauthorized
const ListGroupsUnauthorizedCode int = 401

// ListGroupsUnauthorized Authorization token is missing or invalid.
//
// swagger:response listGroupsUnauthorized
type ListGroupsUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListGroupsUnauthorized creates ListGroupsUnauthorized with default headers values
func NewListGroupsUnauthorized() *ListGroupsUnauthorized {

	return &ListGroupsUnauthorized{}
}

// WithPayload adds the payload to the list groups unauthorized response
func (o *ListGroupsUnauthorized) WithPayload(payload *models.AppError) *ListGroupsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups unauthorized response
func (o *ListGroupsUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListGroupsInternalServerErrorCode is the HTTP code returned for type ListGroupsInternalServerError
const ListGroupsInternalServerErrorCode int = 500

// ListGroupsInternalServerError Groups could not be listed.
//
// swagger:response listGroupsInternalServerError
type ListGroupsInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListGroupsInternalServerError creates ListGroupsInternalServerError with default headers values
func NewListGroupsInternalServerError() *ListGroupsInternalServerError {

	return &ListGroupsInternalServerError{}
}

// WithPayload adds the payload to the list groups internal server error response
func (o *ListGroupsInternalServerError) WithPayload(payload *models.AppError) *ListGroupsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list groups internal server error response
func (o *ListGroupsInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
