// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ListGroupSatellitesOKCode is the HTTP code returned for type ListGroupSatellitesOK
const ListGroupSatellitesOKCode int = 200

// ListGroupSatellitesOK Group satellites returned.
//
// swagger:response listGroupSatellitesOK
type ListGroupSatellitesOK struct {

	// In: Body
	Payload []*models.APIGroupSatellite `json:"body,omitempty"`
}

// NewListGroupSatellitesOK creates ListGroupSatellitesOK with default headers values
func NewListGroupSatellitesOK() *ListGroupSatellitesOK {

	return &ListGroupSatellitesOK{}
}

// WithPayload adds the payload to the list group satellites o k response
func (o *ListGroupSatellitesOK) WithPayload(payload []*models.APIGroupSatellite) *ListGroupSatellitesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list group satellites o k response
func (o *ListGroupSatellitesOK) SetPayload(payload []*models.APIGroupSatellite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupSatellitesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.APIGroupSatellite, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListGroupSatellitesUnauthorizedCode is the HTTP code returned for type ListGroupSatellitesUnauthorized
const ListGroupSatellitesUnauthorizedCode int = 401

// ListGroupSatellitesUnauthorized Authorization token is missing or invalid.
//
// swagger:response listGroupSatellitesUnauthorized
type ListGroupSatellitesUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListGroupSatellitesUnauthorized creates ListGroupSatellitesUnauthorized with default headers values
func NewListGroupSatellitesUnauthorized() *ListGroupSatellitesUnauthorized {

	return &ListGroupSatellitesUnauthorized{}
}

// WithPayload adds the payload to the list group satellites unauthorized response
func (o *ListGroupSatellitesUnauthorized) WithPayload(payload *models.AppError) *ListGroupSatellitesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list group satellites unauthorized response
func (o *ListGroupSatellitesUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupSatellitesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListGroupSatellitesNotFoundCode is the HTTP code returned for type ListGroupSatellitesNotFound
const ListGroupSatellitesNotFoundCode int = 404

// ListGroupSatellitesNotFound Group was not found.
//
// swagger:response listGroupSatellitesNotFound
type ListGroupSatellitesNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListGroupSatellitesNotFound creates ListGroupSatellitesNotFound with default headers values
func NewListGroupSatellitesNotFound() *ListGroupSatellitesNotFound {

	return &ListGroupSatellitesNotFound{}
}

// WithPayload adds the payload to the list group satellites not found response
func (o *ListGroupSatellitesNotFound) WithPayload(payload *models.AppError) *ListGroupSatellitesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list group satellites not found response
func (o *ListGroupSatellitesNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupSatellitesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListGroupSatellitesInternalServerErrorCode is the HTTP code returned for type ListGroupSatellitesInternalServerError
const ListGroupSatellitesInternalServerErrorCode int = 500

// ListGroupSatellitesInternalServerError Group satellites could not be listed.
//
// swagger:response listGroupSatellitesInternalServerError
type ListGroupSatellitesInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListGroupSatellitesInternalServerError creates ListGroupSatellitesInternalServerError with default headers values
func NewListGroupSatellitesInternalServerError() *ListGroupSatellitesInternalServerError {

	return &ListGroupSatellitesInternalServerError{}
}

// WithPayload adds the payload to the list group satellites internal server error response
func (o *ListGroupSatellitesInternalServerError) WithPayload(payload *models.AppError) *ListGroupSatellitesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list group satellites internal server error response
func (o *ListGroupSatellitesInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListGroupSatellitesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
