// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListGroupSatellitesHandlerFunc turns a function with the right signature into a list group satellites handler
type ListGroupSatellitesHandlerFunc func(ListGroupSatellitesParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn ListGroupSatellitesHandlerFunc) Handle(params ListGroupSatellitesParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// ListGroupSatellitesHandler interface for that can handle valid list group satellites params
type ListGroupSatellitesHandler interface {
	Handle(ListGroupSatellitesParams, any) middleware.Responder
}

// NewListGroupSatellites creates a new http.Handler for the list group satellites operation
func NewListGroupSatellites(ctx *middleware.Context, handler ListGroupSatellitesHandler) *ListGroupSatellites {
	return &ListGroupSatellites{Context: ctx, Handler: handler}
}

// ListGroupSatellites swagger:route GET /api/groups/{group}/satellites groups listGroupSatellites
//
// Lists satellites attached to a group.
type ListGroupSatellites struct {
	Context *middleware.Context
	Handler ListGroupSatellitesHandler
}

func (o *ListGroupSatellites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewListGroupSatellitesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
