// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// RemoveSatelliteFromGroupOKCode is the HTTP code returned for type RemoveSatelliteFromGroupOK
const RemoveSatelliteFromGroupOKCode int = 200

// RemoveSatelliteFromGroupOK Satellite removed from the group.
//
// swagger:response removeSatelliteFromGroupOK
type RemoveSatelliteFromGroupOK struct {

	// In: Body
	Payload models.APIEmptyObject `json:"body,omitempty"`
}

// NewRemoveSatelliteFromGroupOK creates RemoveSatelliteFromGroupOK with default headers values
func NewRemoveSatelliteFromGroupOK() *RemoveSatelliteFromGroupOK {

	return &RemoveSatelliteFromGroupOK{}
}

// WithPayload adds the payload to the remove satellite from group o k response
func (o *RemoveSatelliteFromGroupOK) WithPayload(payload models.APIEmptyObject) *RemoveSatelliteFromGroupOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove satellite from group o k response
func (o *RemoveSatelliteFromGroupOK) SetPayload(payload models.APIEmptyObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveSatelliteFromGroupOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// RemoveSatelliteFromGroupBadRequestCode is the HTTP code returned for type RemoveSatelliteFromGroupBadRequest
const RemoveSatelliteFromGroupBadRequestCode int = 400

// RemoveSatelliteFromGroupBadRequest Satellite or group is invalid or not found.
//
// swagger:response removeSatelliteFromGroupBadRequest
type RemoveSatelliteFromGroupBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRemoveSatelliteFromGroupBadRequest creates RemoveSatelliteFromGroupBadRequest with default headers values
func NewRemoveSatelliteFromGroupBadRequest() *RemoveSatelliteFromGroupBadRequest {

	return &RemoveSatelliteFromGroupBadRequest{}
}

// WithPayload adds the payload to the remove satellite from group bad request response
func (o *RemoveSatelliteFromGroupBadRequest) WithPayload(payload *models.AppError) *RemoveSatelliteFromGroupBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove satellite from group bad request response
func (o *RemoveSatelliteFromGroupBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveSatelliteFromGroupBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RemoveSatelliteFromGroupUnauthorizedCode is the HTTP code returned for type RemoveSatelliteFromGroupUnauthorized
const RemoveSatelliteFromGroupUnauthorizedCode int = 401

// RemoveSatelliteFromGroupUnauthorized Authorization token is missing or invalid.
//
// swagger:response removeSatelliteFromGroupUnauthorized
type RemoveSatelliteFromGroupUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRemoveSatelliteFromGroupUnauthorized creates RemoveSatelliteFromGroupUnauthorized with default headers values
func NewRemoveSatelliteFromGroupUnauthorized() *RemoveSatelliteFromGroupUnauthorized {

	return &RemoveSatelliteFromGroupUnauthorized{}
}

// WithPayload adds the payload to the remove satellite from group unauthorized response
func (o *RemoveSatelliteFromGroupUnauthorized) WithPayload(payload *models.AppError) *RemoveSatelliteFromGroupUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove satellite from group unauthorized response
func (o *RemoveSatelliteFromGroupUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveSatelliteFromGroupUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RemoveSatelliteFromGroupInternalServerErrorCode is the HTTP code returned for type RemoveSatelliteFromGroupInternalServerError
const RemoveSatelliteFromGroupInternalServerErrorCode int = 500

// RemoveSatelliteFromGroupInternalServerError Satellite could not be removed from the group.
//
// swagger:response removeSatelliteFromGroupInternalServerError
type RemoveSatelliteFromGroupInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRemoveSatelliteFromGroupInternalServerError creates RemoveSatelliteFromGroupInternalServerError with default headers values
func NewRemoveSatelliteFromGroupInternalServerError() *RemoveSatelliteFromGroupInternalServerError {

	return &RemoveSatelliteFromGroupInternalServerError{}
}

// WithPayload adds the payload to the remove satellite from group internal server error response
func (o *RemoveSatelliteFromGroupInternalServerError) WithPayload(payload *models.AppError) *RemoveSatelliteFromGroupInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the remove satellite from group internal server error response
func (o *RemoveSatelliteFromGroupInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RemoveSatelliteFromGroupInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
