// Code generated by go-swagger; DO NOT EDIT.

package groups

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SyncGroupHandlerFunc turns a function with the right signature into a sync group handler
type SyncGroupHandlerFunc func(SyncGroupParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn SyncGroupHandlerFunc) Handle(params SyncGroupParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// SyncGroupHandler interface for that can handle valid sync group params
type SyncGroupHandler interface {
	Handle(SyncGroupParams, any) middleware.Responder
}

// NewSyncGroup creates a new http.Handler for the sync group operation
func NewSyncGroup(ctx *middleware.Context, handler SyncGroupHandler) *SyncGroup {
	return &SyncGroup{Context: ctx, Handler: handler}
}

// SyncGroup swagger:route POST /api/groups/sync groups syncGroup
//
// Synchronizes a group state artifact.
type SyncGroup struct {
	Context *middleware.Context
	Handler SyncGroupHandler
}

func (o *SyncGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewSyncGroupParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
