// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"encoding/json"
	"time"
)

type Config struct {
	ID          int32
	ConfigName  string
	RegistryUrl string
	Config      json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Group struct {
	ID          int32
	GroupName   string
	RegistryUrl string
	Projects    []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RobotAccount struct {
	ID          int32
	RobotName   string
	RobotSecret string
	RobotID     string
	SatelliteID int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Satellite struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SatelliteConfig struct {
	SatelliteID int32
	ConfigID    int32
}

type SatelliteGroup struct {
	SatelliteID int32
	GroupID     int32
}

type SatelliteToken struct {
	ID          int32
	SatelliteID int32
	Token       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
