// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Group struct {
	ID        int32
	GroupName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GroupImage struct {
	GroupID int32
	ImageID int32
}

type Image struct {
	ID         int32
	Registry   string
	Repository string
	Tag        string
	Digest     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Label struct {
	ID        int32
	LabelName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LabelImage struct {
	LabelID int32
	ImageID int32
}

type Project struct {
	ID        int32
	Projects  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Robot struct {
	ID          int32
	RobotName   string
	Secret      string
	SatelliteID sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RobotAccount struct {
	ID          int32
	RobotName   string
	RobotSecret string
	SatelliteID int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RobotProject struct {
	RobotID   int32
	ProjectID int32
}

type Satellite struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SatelliteGroup struct {
	SatelliteID int32
	GroupID     int32
}

type SatelliteLabel struct {
	SatelliteID int32
	LabelID     int32
}

type SatelliteToken struct {
	ID          int32
	SatelliteID int32
	Token       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
