// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Config struct {
	ID          int32
	ConfigName  string
	RegistryUrl string
	Config      json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Group struct {
	ID          int32
	GroupName   string
	RegistryUrl string
	Projects    []string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type LoginAttempt struct {
	ID          int32
	Username    string
	FailedCount int32
	LockedUntil sql.NullTime
	LastAttempt time.Time
}

type RobotAccount struct {
	ID          int32
	RobotName   string
	RobotSecret string
	RobotID     string
	SatelliteID int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Satellite struct {
	ID                int32
	Name              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastSeen          sql.NullTime
	HeartbeatInterval sql.NullString
}

type SatelliteConfig struct {
	SatelliteID int32
	ConfigID    int32
}

type SatelliteGroup struct {
	SatelliteID int32
	GroupID     int32
}

type SatelliteStatus struct {
	ID                 int32
	SatelliteID        int32
	Activity           string
	LatestStateDigest  sql.NullString
	LatestConfigDigest sql.NullString
	CpuPercent         sql.NullString
	MemoryUsedBytes    sql.NullInt64
	StorageUsedBytes   sql.NullInt64
	LastSyncDurationMs sql.NullInt64
	ImageCount         sql.NullInt32
	ReportedAt         time.Time
	CreatedAt          time.Time
}

type SatelliteToken struct {
	ID          int32
	SatelliteID int32
	Token       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ExpiresAt   time.Time
}

type Session struct {
	ID        int32
	UserID    int32
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
