// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: satellite_status.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const deleteOldSatelliteStatus = `-- name: DeleteOldSatelliteStatus :exec
DELETE FROM satellite_status
WHERE created_at < NOW() - INTERVAL '1 day' * $1
`

func (q *Queries) DeleteOldSatelliteStatus(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteOldSatelliteStatus, dollar_1)
	return err
}

const getActiveSatellites = `-- name: GetActiveSatellites :many
SELECT s.id, s.name, s.created_at, s.updated_at, s.last_seen, s.heartbeat_interval,
       COALESCE(ss.activity, '') as last_activity,
       COALESCE(ss.reported_at, s.last_seen) as last_status_time
FROM satellites s
LEFT JOIN LATERAL (
    SELECT activity, reported_at
    FROM satellite_status
    WHERE satellite_id = s.id
    ORDER BY created_at DESC LIMIT 1
) ss ON true
WHERE s.last_seen IS NOT NULL
  AND s.last_seen > NOW() - (
    CASE
      WHEN s.heartbeat_interval LIKE '@every %'
      THEN (SUBSTRING(s.heartbeat_interval FROM 8)::INTERVAL * 3)
      ELSE INTERVAL '15 minutes'
    END
  )
`

type GetActiveSatellitesRow struct {
	ID                int32
	Name              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastSeen          sql.NullTime
	HeartbeatInterval sql.NullString
	LastActivity      string
	LastStatusTime    time.Time
}

func (q *Queries) GetActiveSatellites(ctx context.Context) ([]GetActiveSatellitesRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSatellites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSatellitesRow
	for rows.Next() {
		var i GetActiveSatellitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeen,
			&i.HeartbeatInterval,
			&i.LastActivity,
			&i.LastStatusTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestSatelliteStatus = `-- name: GetLatestSatelliteStatus :one
SELECT id, satellite_id, activity, latest_state_digest, latest_config_digest, cpu_percent, memory_used_bytes, storage_used_bytes, last_sync_duration_ms, image_count, reported_at, created_at FROM satellite_status
WHERE satellite_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestSatelliteStatus(ctx context.Context, satelliteID int32) (SatelliteStatus, error) {
	row := q.db.QueryRowContext(ctx, getLatestSatelliteStatus, satelliteID)
	var i SatelliteStatus
	err := row.Scan(
		&i.ID,
		&i.SatelliteID,
		&i.Activity,
		&i.LatestStateDigest,
		&i.LatestConfigDigest,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.StorageUsedBytes,
		&i.LastSyncDurationMs,
		&i.ImageCount,
		&i.ReportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSatelliteStatusHistory = `-- name: GetSatelliteStatusHistory :many
SELECT id, satellite_id, activity, latest_state_digest, latest_config_digest, cpu_percent, memory_used_bytes, storage_used_bytes, last_sync_duration_ms, image_count, reported_at, created_at FROM satellite_status
WHERE satellite_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetSatelliteStatusHistoryParams struct {
	SatelliteID int32
	Limit       int32
}

func (q *Queries) GetSatelliteStatusHistory(ctx context.Context, arg GetSatelliteStatusHistoryParams) ([]SatelliteStatus, error) {
	rows, err := q.db.QueryContext(ctx, getSatelliteStatusHistory, arg.SatelliteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SatelliteStatus
	for rows.Next() {
		var i SatelliteStatus
		if err := rows.Scan(
			&i.ID,
			&i.SatelliteID,
			&i.Activity,
			&i.LatestStateDigest,
			&i.LatestConfigDigest,
			&i.CpuPercent,
			&i.MemoryUsedBytes,
			&i.StorageUsedBytes,
			&i.LastSyncDurationMs,
			&i.ImageCount,
			&i.ReportedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleSatellites = `-- name: GetStaleSatellites :many
SELECT s.id, s.name, s.created_at, s.updated_at, s.last_seen, s.heartbeat_interval,
       EXTRACT(EPOCH FROM (NOW() - s.last_seen))::BIGINT as seconds_since_seen
FROM satellites s
WHERE s.last_seen IS NOT NULL
  AND s.heartbeat_interval IS NOT NULL
  AND s.last_seen < NOW() - (
    CASE
      WHEN s.heartbeat_interval LIKE '@every %'
      THEN (SUBSTRING(s.heartbeat_interval FROM 8)::INTERVAL * 3)
      ELSE INTERVAL '15 minutes'
    END
  )
`

type GetStaleSatellitesRow struct {
	ID                int32
	Name              string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	LastSeen          sql.NullTime
	HeartbeatInterval sql.NullString
	SecondsSinceSeen  int64
}

func (q *Queries) GetStaleSatellites(ctx context.Context) ([]GetStaleSatellitesRow, error) {
	rows, err := q.db.QueryContext(ctx, getStaleSatellites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaleSatellitesRow
	for rows.Next() {
		var i GetStaleSatellitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeen,
			&i.HeartbeatInterval,
			&i.SecondsSinceSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSatelliteStatus = `-- name: InsertSatelliteStatus :one
INSERT INTO satellite_status (
    satellite_id, activity, latest_state_digest, latest_config_digest,
    cpu_percent, memory_used_bytes, storage_used_bytes,
    last_sync_duration_ms, image_count, reported_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, satellite_id, activity, latest_state_digest, latest_config_digest, cpu_percent, memory_used_bytes, storage_used_bytes, last_sync_duration_ms, image_count, reported_at, created_at
`

type InsertSatelliteStatusParams struct {
	SatelliteID        int32
	Activity           string
	LatestStateDigest  sql.NullString
	LatestConfigDigest sql.NullString
	CpuPercent         sql.NullString
	MemoryUsedBytes    sql.NullInt64
	StorageUsedBytes   sql.NullInt64
	LastSyncDurationMs sql.NullInt64
	ImageCount         sql.NullInt32
	ReportedAt         time.Time
}

func (q *Queries) InsertSatelliteStatus(ctx context.Context, arg InsertSatelliteStatusParams) (SatelliteStatus, error) {
	row := q.db.QueryRowContext(ctx, insertSatelliteStatus,
		arg.SatelliteID,
		arg.Activity,
		arg.LatestStateDigest,
		arg.LatestConfigDigest,
		arg.CpuPercent,
		arg.MemoryUsedBytes,
		arg.StorageUsedBytes,
		arg.LastSyncDurationMs,
		arg.ImageCount,
		arg.ReportedAt,
	)
	var i SatelliteStatus
	err := row.Scan(
		&i.ID,
		&i.SatelliteID,
		&i.Activity,
		&i.LatestStateDigest,
		&i.LatestConfigDigest,
		&i.CpuPercent,
		&i.MemoryUsedBytes,
		&i.StorageUsedBytes,
		&i.LastSyncDurationMs,
		&i.ImageCount,
		&i.ReportedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSatelliteLastSeen = `-- name: UpdateSatelliteLastSeen :exec
UPDATE satellites SET last_seen = NOW(), heartbeat_interval = $2 WHERE id = $1
`

type UpdateSatelliteLastSeenParams struct {
	ID                int32
	HeartbeatInterval sql.NullString
}

func (q *Queries) UpdateSatelliteLastSeen(ctx context.Context, arg UpdateSatelliteLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, updateSatelliteLastSeen, arg.ID, arg.HeartbeatInterval)
	return err
}
