// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vulnerabilities.sql

package database

import (
	"context"
	"database/sql"
)

const deleteVulnerabilitiesForArtifact = `-- name: DeleteVulnerabilitiesForArtifact :exec
DELETE FROM vulnerabilities
WHERE artifact_digest = $1
`

func (q *Queries) DeleteVulnerabilitiesForArtifact(ctx context.Context, artifactDigest string) error {
	_, err := q.db.ExecContext(ctx, deleteVulnerabilitiesForArtifact, artifactDigest)
	return err
}

const getVulnerabilitiesByArtifact = `-- name: GetVulnerabilitiesByArtifact :many
SELECT id, artifact_digest, cve_id, severity, package_name, installed_version, fixed_version, description, scanner, scanned_at, created_at FROM vulnerabilities
WHERE artifact_digest = $1
ORDER BY severity DESC
`

func (q *Queries) GetVulnerabilitiesByArtifact(ctx context.Context, artifactDigest string) ([]Vulnerability, error) {
	rows, err := q.db.QueryContext(ctx, getVulnerabilitiesByArtifact, artifactDigest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vulnerability
	for rows.Next() {
		var i Vulnerability
		if err := rows.Scan(
			&i.ID,
			&i.ArtifactDigest,
			&i.CveID,
			&i.Severity,
			&i.PackageName,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.Description,
			&i.Scanner,
			&i.ScannedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVulnerability = `-- name: UpsertVulnerability :exec

INSERT INTO vulnerabilities (
    artifact_digest,
    cve_id,
    severity,
    package_name,
    installed_version,
    fixed_version,
    description,
    scanner,
    scanned_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (artifact_digest, cve_id) DO UPDATE SET
    severity = EXCLUDED.severity,
    package_name = EXCLUDED.package_name,
    installed_version = EXCLUDED.installed_version,
    fixed_version = EXCLUDED.fixed_version,
    description = EXCLUDED.description,
    scanner = EXCLUDED.scanner,
    scanned_at = EXCLUDED.scanned_at
`

type UpsertVulnerabilityParams struct {
	ArtifactDigest   string
	CveID            string
	Severity         string
	PackageName      sql.NullString
	InstalledVersion sql.NullString
	FixedVersion     sql.NullString
	Description      sql.NullString
	Scanner          sql.NullString
	ScannedAt        sql.NullTime
}

// ground-control/sql/queries/vulnerabilities.sql
func (q *Queries) UpsertVulnerability(ctx context.Context, arg UpsertVulnerabilityParams) error {
	_, err := q.db.ExecContext(ctx, upsertVulnerability,
		arg.ArtifactDigest,
		arg.CveID,
		arg.Severity,
		arg.PackageName,
		arg.InstalledVersion,
		arg.FixedVersion,
		arg.Description,
		arg.Scanner,
		arg.ScannedAt,
	)
	return err
}
