name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A brief summary of the feature request
      placeholder: What feature would you like to see?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like
      placeholder: Describe what you want to happen
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: What other solutions have you considered?
    validations:
      required: false
  - type: textarea
    id: expected_file_changes
    attributes:
      label: Expected File Changes
      description: If you know what files should be changed, list them here
      placeholder: List any expected file changes here
    validations:
      required: false