name: General Issue
description: For issues that don't fit other categories
title: "[GENERAL] "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please provide details about your issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue
      placeholder: What is the issue?
    validations:
      required: false

  - type: textarea
    id: expected_file_changes
    attributes:
      label: Expected File Changes
      description: If you know what files should be changed, list them here
      placeholder: List any expected file changes here
    validations:
      required: false