// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"time"

	flags "github.com/jessevdk/go-flags"
	"github.com/joho/godotenv"

	"github.com/container-registry/harbor-satellite/internal/env"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/harborhealth"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/migrator"
	swaggerhandlers "github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/handlers"
	swaggerserversrv "github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server"
	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/server/operations"
	"github.com/go-openapi/loads"
)

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	_ = godotenv.Load(".env") //nolint:errcheck // .env file is optional
	if err := env.LoadGC(); err != nil {
		return fmt.Errorf("load environment: %w", err)
	}

	if err := harborhealth.CheckHealth(); err != nil {
		return fmt.Errorf("check Harbor health: %w", err)
	}

	migrator.DoMigrations()
	if err := swaggerhandlers.Initialize(context.Background()); err != nil {
		return err
	}
	defer func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := swaggerserversrv.ShutdownApplication(ctx); err != nil {
			log.Printf("Ground Control resource shutdown error: %v", err)
		}
	}()
	if err := swaggerhandlers.StartBackgroundJobs(); err != nil {
		return err
	}
	if err := swaggerserversrv.PrepareRuntime(); err != nil {
		return fmt.Errorf("prepare server runtime: %w", err)
	}

	swaggerSpec, err := loads.Embedded(swaggerserversrv.SwaggerJSON, swaggerserversrv.FlatSwaggerJSON)
	if err != nil {
		return fmt.Errorf("load embedded Swagger specification: %w", err)
	}

	api := operations.NewGroundControlAPI(swaggerSpec)
	server := swaggerserversrv.NewServer(api)
	server.ConfigureFlags() // inject API-specific custom flags. Must be called before args parsing

	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Ground Control"
	parser.LongDescription = "Ground Control manages Harbor Satellite registration, configuration,\ngroup membership, user administration, status reporting, and SPIRE/SPIFFE\nbootstrap flows.\n"
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			return fmt.Errorf("add command-line option group: %w", err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		fe := new(flags.Error)
		if errors.As(err, &fe) && fe.Type == flags.ErrHelp {
			return nil
		}
		return fmt.Errorf("parse command-line options: %w", err)
	}

	server.ConfigureAPI() // configure handlers, routes and middleware

	if err := server.Serve(); err != nil {
		_ = server.Shutdown()
		return fmt.Errorf("serve Ground Control API: %w", err)
	}
	return nil
}
