// Code generated by go-swagger; DO NOT EDIT.

package health

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewHealthParams creates a new HealthParams object
//
// There are no default values defined in the spec.
func NewHealthParams() HealthParams {

	return HealthParams{}
}

// HealthParams contains all the bound params for the health operation
// typically these are obtained from a http.Request
//
// swagger:parameters health
type HealthParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewHealthParams() beforehand.
func (o *HealthParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
