// Code generated by go-swagger; DO NOT EDIT.

package health

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PingOKCode is the HTTP code returned for type PingOK
const PingOKCode int = 200

// PingOK Server is reachable and returns pong.
//
// swagger:response pingOK
type PingOK struct {

	// In: Body
	Payload string `json:"body,omitempty"`
}

// NewPingOK creates PingOK with default headers values
func NewPingOK() *PingOK {

	return &PingOK{}
}

// WithPayload adds the payload to the ping o k response
func (o *PingOK) WithPayload(payload string) *PingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ping o k response
func (o *PingOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
