// Code generated by go-swagger; DO NOT EDIT.

package auth

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// LogoutNoContentCode is the HTTP code returned for type LogoutNoContent
const LogoutNoContentCode int = 204

// LogoutNoContent Session deleted.
//
// swagger:response logoutNoContent
type LogoutNoContent struct {
}

// NewLogoutNoContent creates LogoutNoContent with default headers values
func NewLogoutNoContent() *LogoutNoContent {

	return &LogoutNoContent{}
}

// WriteResponse to the client
func (o *LogoutNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// LogoutUnauthorizedCode is the HTTP code returned for type LogoutUnauthorized
const LogoutUnauthorizedCode int = 401

// LogoutUnauthorized Authorization token is missing or invalid.
//
// swagger:response logoutUnauthorized
type LogoutUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewLogoutUnauthorized creates LogoutUnauthorized with default headers values
func NewLogoutUnauthorized() *LogoutUnauthorized {

	return &LogoutUnauthorized{}
}

// WithPayload adds the payload to the logout unauthorized response
func (o *LogoutUnauthorized) WithPayload(payload *models.AppError) *LogoutUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout unauthorized response
func (o *LogoutUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogoutInternalServerErrorCode is the HTTP code returned for type LogoutInternalServerError
const LogoutInternalServerErrorCode int = 500

// LogoutInternalServerError Session could not be deleted.
//
// swagger:response logoutInternalServerError
type LogoutInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewLogoutInternalServerError creates LogoutInternalServerError with default headers values
func NewLogoutInternalServerError() *LogoutInternalServerError {

	return &LogoutInternalServerError{}
}

// WithPayload adds the payload to the logout internal server error response
func (o *LogoutInternalServerError) WithPayload(payload *models.AppError) *LogoutInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout internal server error response
func (o *LogoutInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
