// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ChangeUserPasswordNoContentCode is the HTTP code returned for type ChangeUserPasswordNoContent
const ChangeUserPasswordNoContentCode int = 204

// ChangeUserPasswordNoContent Password reset and user sessions invalidated.
//
// swagger:response changeUserPasswordNoContent
type ChangeUserPasswordNoContent struct {
}

// NewChangeUserPasswordNoContent creates ChangeUserPasswordNoContent with default headers values
func NewChangeUserPasswordNoContent() *ChangeUserPasswordNoContent {

	return &ChangeUserPasswordNoContent{}
}

// WriteResponse to the client
func (o *ChangeUserPasswordNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ChangeUserPasswordBadRequestCode is the HTTP code returned for type ChangeUserPasswordBadRequest
const ChangeUserPasswordBadRequestCode int = 400

// ChangeUserPasswordBadRequest Request body or new password is invalid.
//
// swagger:response changeUserPasswordBadRequest
type ChangeUserPasswordBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeUserPasswordBadRequest creates ChangeUserPasswordBadRequest with default headers values
func NewChangeUserPasswordBadRequest() *ChangeUserPasswordBadRequest {

	return &ChangeUserPasswordBadRequest{}
}

// WithPayload adds the payload to the change user password bad request response
func (o *ChangeUserPasswordBadRequest) WithPayload(payload *models.AppError) *ChangeUserPasswordBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change user password bad request response
func (o *ChangeUserPasswordBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeUserPasswordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChangeUserPasswordUnauthorizedCode is the HTTP code returned for type ChangeUserPasswordUnauthorized
const ChangeUserPasswordUnauthorizedCode int = 401

// ChangeUserPasswordUnauthorized Authorization token is missing or invalid.
//
// swagger:response changeUserPasswordUnauthorized
type ChangeUserPasswordUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeUserPasswordUnauthorized creates ChangeUserPasswordUnauthorized with default headers values
func NewChangeUserPasswordUnauthorized() *ChangeUserPasswordUnauthorized {

	return &ChangeUserPasswordUnauthorized{}
}

// WithPayload adds the payload to the change user password unauthorized response
func (o *ChangeUserPasswordUnauthorized) WithPayload(payload *models.AppError) *ChangeUserPasswordUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change user password unauthorized response
func (o *ChangeUserPasswordUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeUserPasswordUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChangeUserPasswordForbiddenCode is the HTTP code returned for type ChangeUserPasswordForbidden
const ChangeUserPasswordForbiddenCode int = 403

// ChangeUserPasswordForbidden System administrator role is required.
//
// swagger:response changeUserPasswordForbidden
type ChangeUserPasswordForbidden struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeUserPasswordForbidden creates ChangeUserPasswordForbidden with default headers values
func NewChangeUserPasswordForbidden() *ChangeUserPasswordForbidden {

	return &ChangeUserPasswordForbidden{}
}

// WithPayload adds the payload to the change user password forbidden response
func (o *ChangeUserPasswordForbidden) WithPayload(payload *models.AppError) *ChangeUserPasswordForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change user password forbidden response
func (o *ChangeUserPasswordForbidden) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeUserPasswordForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChangeUserPasswordNotFoundCode is the HTTP code returned for type ChangeUserPasswordNotFound
const ChangeUserPasswordNotFoundCode int = 404

// ChangeUserPasswordNotFound User was not found.
//
// swagger:response changeUserPasswordNotFound
type ChangeUserPasswordNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeUserPasswordNotFound creates ChangeUserPasswordNotFound with default headers values
func NewChangeUserPasswordNotFound() *ChangeUserPasswordNotFound {

	return &ChangeUserPasswordNotFound{}
}

// WithPayload adds the payload to the change user password not found response
func (o *ChangeUserPasswordNotFound) WithPayload(payload *models.AppError) *ChangeUserPasswordNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change user password not found response
func (o *ChangeUserPasswordNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeUserPasswordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChangeUserPasswordInternalServerErrorCode is the HTTP code returned for type ChangeUserPasswordInternalServerError
const ChangeUserPasswordInternalServerErrorCode int = 500

// ChangeUserPasswordInternalServerError Password could not be reset.
//
// swagger:response changeUserPasswordInternalServerError
type ChangeUserPasswordInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeUserPasswordInternalServerError creates ChangeUserPasswordInternalServerError with default headers values
func NewChangeUserPasswordInternalServerError() *ChangeUserPasswordInternalServerError {

	return &ChangeUserPasswordInternalServerError{}
}

// WithPayload adds the payload to the change user password internal server error response
func (o *ChangeUserPasswordInternalServerError) WithPayload(payload *models.AppError) *ChangeUserPasswordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change user password internal server error response
func (o *ChangeUserPasswordInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeUserPasswordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
