// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ChangeUserPasswordHandlerFunc turns a function with the right signature into a change user password handler
type ChangeUserPasswordHandlerFunc func(ChangeUserPasswordParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn ChangeUserPasswordHandlerFunc) Handle(params ChangeUserPasswordParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// ChangeUserPasswordHandler interface for that can handle valid change user password params
type ChangeUserPasswordHandler interface {
	Handle(ChangeUserPasswordParams, any) middleware.Responder
}

// NewChangeUserPassword creates a new http.Handler for the change user password operation
func NewChangeUserPassword(ctx *middleware.Context, handler ChangeUserPasswordHandler) *ChangeUserPassword {
	return &ChangeUserPassword{Context: ctx, Handler: handler}
}

// ChangeUserPassword swagger:route PATCH /api/users/{username}/password users changeUserPassword
//
// Resets a user's password.
type ChangeUserPassword struct {
	Context *middleware.Context
	Handler ChangeUserPasswordHandler
}

func (o *ChangeUserPassword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewChangeUserPasswordParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
