// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ChangeOwnPasswordNoContentCode is the HTTP code returned for type ChangeOwnPasswordNoContent
const ChangeOwnPasswordNoContentCode int = 204

// ChangeOwnPasswordNoContent Password changed and sessions invalidated.
//
// swagger:response changeOwnPasswordNoContent
type ChangeOwnPasswordNoContent struct {
}

// NewChangeOwnPasswordNoContent creates ChangeOwnPasswordNoContent with default headers values
func NewChangeOwnPasswordNoContent() *ChangeOwnPasswordNoContent {

	return &ChangeOwnPasswordNoContent{}
}

// WriteResponse to the client
func (o *ChangeOwnPasswordNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// ChangeOwnPasswordBadRequestCode is the HTTP code returned for type ChangeOwnPasswordBadRequest
const ChangeOwnPasswordBadRequestCode int = 400

// ChangeOwnPasswordBadRequest Request body or new password is invalid.
//
// swagger:response changeOwnPasswordBadRequest
type ChangeOwnPasswordBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeOwnPasswordBadRequest creates ChangeOwnPasswordBadRequest with default headers values
func NewChangeOwnPasswordBadRequest() *ChangeOwnPasswordBadRequest {

	return &ChangeOwnPasswordBadRequest{}
}

// WithPayload adds the payload to the change own password bad request response
func (o *ChangeOwnPasswordBadRequest) WithPayload(payload *models.AppError) *ChangeOwnPasswordBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change own password bad request response
func (o *ChangeOwnPasswordBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeOwnPasswordBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChangeOwnPasswordUnauthorizedCode is the HTTP code returned for type ChangeOwnPasswordUnauthorized
const ChangeOwnPasswordUnauthorizedCode int = 401

// ChangeOwnPasswordUnauthorized Authorization token is missing, invalid, or current password is incorrect.
//
// swagger:response changeOwnPasswordUnauthorized
type ChangeOwnPasswordUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeOwnPasswordUnauthorized creates ChangeOwnPasswordUnauthorized with default headers values
func NewChangeOwnPasswordUnauthorized() *ChangeOwnPasswordUnauthorized {

	return &ChangeOwnPasswordUnauthorized{}
}

// WithPayload adds the payload to the change own password unauthorized response
func (o *ChangeOwnPasswordUnauthorized) WithPayload(payload *models.AppError) *ChangeOwnPasswordUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change own password unauthorized response
func (o *ChangeOwnPasswordUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeOwnPasswordUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ChangeOwnPasswordInternalServerErrorCode is the HTTP code returned for type ChangeOwnPasswordInternalServerError
const ChangeOwnPasswordInternalServerErrorCode int = 500

// ChangeOwnPasswordInternalServerError Password could not be changed.
//
// swagger:response changeOwnPasswordInternalServerError
type ChangeOwnPasswordInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewChangeOwnPasswordInternalServerError creates ChangeOwnPasswordInternalServerError with default headers values
func NewChangeOwnPasswordInternalServerError() *ChangeOwnPasswordInternalServerError {

	return &ChangeOwnPasswordInternalServerError{}
}

// WithPayload adds the payload to the change own password internal server error response
func (o *ChangeOwnPasswordInternalServerError) WithPayload(payload *models.AppError) *ChangeOwnPasswordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the change own password internal server error response
func (o *ChangeOwnPasswordInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChangeOwnPasswordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
