// Code generated by go-swagger; DO NOT EDIT.

package users

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ListUsersOKCode is the HTTP code returned for type ListUsersOK
const ListUsersOKCode int = 200

// ListUsersOK Users returned.
//
// swagger:response listUsersOK
type ListUsersOK struct {

	// In: Body
	Payload []*models.UserResponse `json:"body,omitempty"`
}

// NewListUsersOK creates ListUsersOK with default headers values
func NewListUsersOK() *ListUsersOK {

	return &ListUsersOK{}
}

// WithPayload adds the payload to the list users o k response
func (o *ListUsersOK) WithPayload(payload []*models.UserResponse) *ListUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users o k response
func (o *ListUsersOK) SetPayload(payload []*models.UserResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.UserResponse, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListUsersUnauthorizedCode is the HTTP code returned for type ListUsersUnauthorized
const ListUsersUnauthorizedCode int = 401

// ListUsersUnauthorized Authorization token is missing or invalid.
//
// swagger:response listUsersUnauthorized
type ListUsersUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListUsersUnauthorized creates ListUsersUnauthorized with default headers values
func NewListUsersUnauthorized() *ListUsersUnauthorized {

	return &ListUsersUnauthorized{}
}

// WithPayload adds the payload to the list users unauthorized response
func (o *ListUsersUnauthorized) WithPayload(payload *models.AppError) *ListUsersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users unauthorized response
func (o *ListUsersUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListUsersInternalServerErrorCode is the HTTP code returned for type ListUsersInternalServerError
const ListUsersInternalServerErrorCode int = 500

// ListUsersInternalServerError Users could not be listed.
//
// swagger:response listUsersInternalServerError
type ListUsersInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListUsersInternalServerError creates ListUsersInternalServerError with default headers values
func NewListUsersInternalServerError() *ListUsersInternalServerError {

	return &ListUsersInternalServerError{}
}

// WithPayload adds the payload to the list users internal server error response
func (o *ListUsersInternalServerError) WithPayload(payload *models.AppError) *ListUsersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users internal server error response
func (o *ListUsersInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
