// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateConfigHandlerFunc turns a function with the right signature into a create config handler
type CreateConfigHandlerFunc func(CreateConfigParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateConfigHandlerFunc) Handle(params CreateConfigParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// CreateConfigHandler interface for that can handle valid create config params
type CreateConfigHandler interface {
	Handle(CreateConfigParams, any) middleware.Responder
}

// NewCreateConfig creates a new http.Handler for the create config operation
func NewCreateConfig(ctx *middleware.Context, handler CreateConfigHandler) *CreateConfig {
	return &CreateConfig{Context: ctx, Handler: handler}
}

// CreateConfig swagger:route POST /api/configs configs createConfig
//
// Creates a satellite configuration.
type CreateConfig struct {
	Context *middleware.Context
	Handler CreateConfigHandler
}

func (o *CreateConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewCreateConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
