// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// DeleteConfigOKCode is the HTTP code returned for type DeleteConfigOK
const DeleteConfigOKCode int = 200

// DeleteConfigOK Configuration deleted.
//
// swagger:response deleteConfigOK
type DeleteConfigOK struct {

	// In: Body
	Payload models.APIEmptyObject `json:"body,omitempty"`
}

// NewDeleteConfigOK creates DeleteConfigOK with default headers values
func NewDeleteConfigOK() *DeleteConfigOK {

	return &DeleteConfigOK{}
}

// WithPayload adds the payload to the delete config o k response
func (o *DeleteConfigOK) WithPayload(payload models.APIEmptyObject) *DeleteConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config o k response
func (o *DeleteConfigOK) SetPayload(payload models.APIEmptyObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteConfigBadRequestCode is the HTTP code returned for type DeleteConfigBadRequest
const DeleteConfigBadRequestCode int = 400

// DeleteConfigBadRequest Configuration is in use and cannot be deleted.
//
// swagger:response deleteConfigBadRequest
type DeleteConfigBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewDeleteConfigBadRequest creates DeleteConfigBadRequest with default headers values
func NewDeleteConfigBadRequest() *DeleteConfigBadRequest {

	return &DeleteConfigBadRequest{}
}

// WithPayload adds the payload to the delete config bad request response
func (o *DeleteConfigBadRequest) WithPayload(payload *models.AppError) *DeleteConfigBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config bad request response
func (o *DeleteConfigBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigUnauthorizedCode is the HTTP code returned for type DeleteConfigUnauthorized
const DeleteConfigUnauthorizedCode int = 401

// DeleteConfigUnauthorized Authorization token is missing or invalid.
//
// swagger:response deleteConfigUnauthorized
type DeleteConfigUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewDeleteConfigUnauthorized creates DeleteConfigUnauthorized with default headers values
func NewDeleteConfigUnauthorized() *DeleteConfigUnauthorized {

	return &DeleteConfigUnauthorized{}
}

// WithPayload adds the payload to the delete config unauthorized response
func (o *DeleteConfigUnauthorized) WithPayload(payload *models.AppError) *DeleteConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config unauthorized response
func (o *DeleteConfigUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigInternalServerErrorCode is the HTTP code returned for type DeleteConfigInternalServerError
const DeleteConfigInternalServerErrorCode int = 500

// DeleteConfigInternalServerError Configuration could not be deleted.
//
// swagger:response deleteConfigInternalServerError
type DeleteConfigInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewDeleteConfigInternalServerError creates DeleteConfigInternalServerError with default headers values
func NewDeleteConfigInternalServerError() *DeleteConfigInternalServerError {

	return &DeleteConfigInternalServerError{}
}

// WithPayload adds the payload to the delete config internal server error response
func (o *DeleteConfigInternalServerError) WithPayload(payload *models.AppError) *DeleteConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config internal server error response
func (o *DeleteConfigInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
