// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigHandlerFunc turns a function with the right signature into a delete config handler
type DeleteConfigHandlerFunc func(DeleteConfigParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigHandlerFunc) Handle(params DeleteConfigParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// DeleteConfigHandler interface for that can handle valid delete config params
type DeleteConfigHandler interface {
	Handle(DeleteConfigParams, any) middleware.Responder
}

// NewDeleteConfig creates a new http.Handler for the delete config operation
func NewDeleteConfig(ctx *middleware.Context, handler DeleteConfigHandler) *DeleteConfig {
	return &DeleteConfig{Context: ctx, Handler: handler}
}

// DeleteConfig swagger:route DELETE /api/configs/{config} configs deleteConfig
//
// Deletes an unused satellite configuration.
type DeleteConfig struct {
	Context *middleware.Context
	Handler DeleteConfigHandler
}

func (o *DeleteConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewDeleteConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
