// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigHandlerFunc turns a function with the right signature into a get config handler
type GetConfigHandlerFunc func(GetConfigParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigHandlerFunc) Handle(params GetConfigParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetConfigHandler interface for that can handle valid get config params
type GetConfigHandler interface {
	Handle(GetConfigParams, any) middleware.Responder
}

// NewGetConfig creates a new http.Handler for the get config operation
func NewGetConfig(ctx *middleware.Context, handler GetConfigHandler) *GetConfig {
	return &GetConfig{Context: ctx, Handler: handler}
}

// GetConfig swagger:route GET /api/configs/{config} configs getConfig
//
// Gets a satellite configuration.
type GetConfig struct {
	Context *middleware.Context
	Handler GetConfigHandler
}

func (o *GetConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
