// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// GetConfigOKCode is the HTTP code returned for type GetConfigOK
const GetConfigOKCode int = 200

// GetConfigOK Configuration returned.
//
// swagger:response getConfigOK
type GetConfigOK struct {

	// In: Body
	Payload *models.APIDatabaseConfig `json:"body,omitempty"`
}

// NewGetConfigOK creates GetConfigOK with default headers values
func NewGetConfigOK() *GetConfigOK {

	return &GetConfigOK{}
}

// WithPayload adds the payload to the get config o k response
func (o *GetConfigOK) WithPayload(payload *models.APIDatabaseConfig) *GetConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config o k response
func (o *GetConfigOK) SetPayload(payload *models.APIDatabaseConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigUnauthorizedCode is the HTTP code returned for type GetConfigUnauthorized
const GetConfigUnauthorizedCode int = 401

// GetConfigUnauthorized Authorization token is missing or invalid.
//
// swagger:response getConfigUnauthorized
type GetConfigUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetConfigUnauthorized creates GetConfigUnauthorized with default headers values
func NewGetConfigUnauthorized() *GetConfigUnauthorized {

	return &GetConfigUnauthorized{}
}

// WithPayload adds the payload to the get config unauthorized response
func (o *GetConfigUnauthorized) WithPayload(payload *models.AppError) *GetConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config unauthorized response
func (o *GetConfigUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigNotFoundCode is the HTTP code returned for type GetConfigNotFound
const GetConfigNotFoundCode int = 404

// GetConfigNotFound Configuration was not found.
//
// swagger:response getConfigNotFound
type GetConfigNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetConfigNotFound creates GetConfigNotFound with default headers values
func NewGetConfigNotFound() *GetConfigNotFound {

	return &GetConfigNotFound{}
}

// WithPayload adds the payload to the get config not found response
func (o *GetConfigNotFound) WithPayload(payload *models.AppError) *GetConfigNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config not found response
func (o *GetConfigNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigInternalServerErrorCode is the HTTP code returned for type GetConfigInternalServerError
const GetConfigInternalServerErrorCode int = 500

// GetConfigInternalServerError Configuration could not be loaded.
//
// swagger:response getConfigInternalServerError
type GetConfigInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetConfigInternalServerError creates GetConfigInternalServerError with default headers values
func NewGetConfigInternalServerError() *GetConfigInternalServerError {

	return &GetConfigInternalServerError{}
}

// WithPayload adds the payload to the get config internal server error response
func (o *GetConfigInternalServerError) WithPayload(payload *models.AppError) *GetConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config internal server error response
func (o *GetConfigInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
