// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ListConfigsOKCode is the HTTP code returned for type ListConfigsOK
const ListConfigsOKCode int = 200

// ListConfigsOK Configurations returned.
//
// swagger:response listConfigsOK
type ListConfigsOK struct {

	// In: Body
	Payload []*models.APIDatabaseConfig `json:"body,omitempty"`
}

// NewListConfigsOK creates ListConfigsOK with default headers values
func NewListConfigsOK() *ListConfigsOK {

	return &ListConfigsOK{}
}

// WithPayload adds the payload to the list configs o k response
func (o *ListConfigsOK) WithPayload(payload []*models.APIDatabaseConfig) *ListConfigsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list configs o k response
func (o *ListConfigsOK) SetPayload(payload []*models.APIDatabaseConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListConfigsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.APIDatabaseConfig, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListConfigsUnauthorizedCode is the HTTP code returned for type ListConfigsUnauthorized
const ListConfigsUnauthorizedCode int = 401

// ListConfigsUnauthorized Authorization token is missing or invalid.
//
// swagger:response listConfigsUnauthorized
type ListConfigsUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListConfigsUnauthorized creates ListConfigsUnauthorized with default headers values
func NewListConfigsUnauthorized() *ListConfigsUnauthorized {

	return &ListConfigsUnauthorized{}
}

// WithPayload adds the payload to the list configs unauthorized response
func (o *ListConfigsUnauthorized) WithPayload(payload *models.AppError) *ListConfigsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list configs unauthorized response
func (o *ListConfigsUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListConfigsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListConfigsInternalServerErrorCode is the HTTP code returned for type ListConfigsInternalServerError
const ListConfigsInternalServerErrorCode int = 500

// ListConfigsInternalServerError Configurations could not be listed.
//
// swagger:response listConfigsInternalServerError
type ListConfigsInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListConfigsInternalServerError creates ListConfigsInternalServerError with default headers values
func NewListConfigsInternalServerError() *ListConfigsInternalServerError {

	return &ListConfigsInternalServerError{}
}

// WithPayload adds the payload to the list configs internal server error response
func (o *ListConfigsInternalServerError) WithPayload(payload *models.AppError) *ListConfigsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list configs internal server error response
func (o *ListConfigsInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListConfigsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
