// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// SetSatelliteConfigOKCode is the HTTP code returned for type SetSatelliteConfigOK
const SetSatelliteConfigOKCode int = 200

// SetSatelliteConfigOK Satellite configuration assignment updated.
//
// swagger:response setSatelliteConfigOK
type SetSatelliteConfigOK struct {

	// In: Body
	Payload models.APIEmptyObject `json:"body,omitempty"`
}

// NewSetSatelliteConfigOK creates SetSatelliteConfigOK with default headers values
func NewSetSatelliteConfigOK() *SetSatelliteConfigOK {

	return &SetSatelliteConfigOK{}
}

// WithPayload adds the payload to the set satellite config o k response
func (o *SetSatelliteConfigOK) WithPayload(payload models.APIEmptyObject) *SetSatelliteConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set satellite config o k response
func (o *SetSatelliteConfigOK) SetPayload(payload models.APIEmptyObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetSatelliteConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// SetSatelliteConfigBadRequestCode is the HTTP code returned for type SetSatelliteConfigBadRequest
const SetSatelliteConfigBadRequestCode int = 400

// SetSatelliteConfigBadRequest Assignment payload, satellite, or configuration is invalid.
//
// swagger:response setSatelliteConfigBadRequest
type SetSatelliteConfigBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSetSatelliteConfigBadRequest creates SetSatelliteConfigBadRequest with default headers values
func NewSetSatelliteConfigBadRequest() *SetSatelliteConfigBadRequest {

	return &SetSatelliteConfigBadRequest{}
}

// WithPayload adds the payload to the set satellite config bad request response
func (o *SetSatelliteConfigBadRequest) WithPayload(payload *models.AppError) *SetSatelliteConfigBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set satellite config bad request response
func (o *SetSatelliteConfigBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetSatelliteConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SetSatelliteConfigUnauthorizedCode is the HTTP code returned for type SetSatelliteConfigUnauthorized
const SetSatelliteConfigUnauthorizedCode int = 401

// SetSatelliteConfigUnauthorized Authorization token is missing or invalid.
//
// swagger:response setSatelliteConfigUnauthorized
type SetSatelliteConfigUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSetSatelliteConfigUnauthorized creates SetSatelliteConfigUnauthorized with default headers values
func NewSetSatelliteConfigUnauthorized() *SetSatelliteConfigUnauthorized {

	return &SetSatelliteConfigUnauthorized{}
}

// WithPayload adds the payload to the set satellite config unauthorized response
func (o *SetSatelliteConfigUnauthorized) WithPayload(payload *models.AppError) *SetSatelliteConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set satellite config unauthorized response
func (o *SetSatelliteConfigUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetSatelliteConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SetSatelliteConfigInternalServerErrorCode is the HTTP code returned for type SetSatelliteConfigInternalServerError
const SetSatelliteConfigInternalServerErrorCode int = 500

// SetSatelliteConfigInternalServerError Satellite configuration assignment could not be updated.
//
// swagger:response setSatelliteConfigInternalServerError
type SetSatelliteConfigInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSetSatelliteConfigInternalServerError creates SetSatelliteConfigInternalServerError with default headers values
func NewSetSatelliteConfigInternalServerError() *SetSatelliteConfigInternalServerError {

	return &SetSatelliteConfigInternalServerError{}
}

// WithPayload adds the payload to the set satellite config internal server error response
func (o *SetSatelliteConfigInternalServerError) WithPayload(payload *models.AppError) *SetSatelliteConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set satellite config internal server error response
func (o *SetSatelliteConfigInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetSatelliteConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
