// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	stderrors "errors"
	"io"
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"
)

// NewSetSatelliteConfigParams creates a new SetSatelliteConfigParams object
//
// There are no default values defined in the spec.
func NewSetSatelliteConfigParams() SetSatelliteConfigParams {

	return SetSatelliteConfigParams{}
}

// SetSatelliteConfigParams contains all the bound params for the set satellite config operation
// typically these are obtained from a http.Request
//
// swagger:parameters setSatelliteConfig
type SetSatelliteConfigParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
	// Satellite configuration assignment payload.
	// Required: true
	// In: body
	Body *models.SatelliteConfigParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSetSatelliteConfigParams() beforehand.
func (o *SetSatelliteConfigParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer func() {
			_ = r.Body.Close()
		}()
		var body models.SatelliteConfigParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if stderrors.Is(err, io.EOF) {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
