// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// UpdateConfigOKCode is the HTTP code returned for type UpdateConfigOK
const UpdateConfigOKCode int = 200

// UpdateConfigOK Configuration updated.
//
// swagger:response updateConfigOK
type UpdateConfigOK struct {

	// In: Body
	Payload *models.APIDatabaseConfig `json:"body,omitempty"`
}

// NewUpdateConfigOK creates UpdateConfigOK with default headers values
func NewUpdateConfigOK() *UpdateConfigOK {

	return &UpdateConfigOK{}
}

// WithPayload adds the payload to the update config o k response
func (o *UpdateConfigOK) WithPayload(payload *models.APIDatabaseConfig) *UpdateConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update config o k response
func (o *UpdateConfigOK) SetPayload(payload *models.APIDatabaseConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConfigBadRequestCode is the HTTP code returned for type UpdateConfigBadRequest
const UpdateConfigBadRequestCode int = 400

// UpdateConfigBadRequest Configuration name, body, or merge patch is invalid.
//
// swagger:response updateConfigBadRequest
type UpdateConfigBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewUpdateConfigBadRequest creates UpdateConfigBadRequest with default headers values
func NewUpdateConfigBadRequest() *UpdateConfigBadRequest {

	return &UpdateConfigBadRequest{}
}

// WithPayload adds the payload to the update config bad request response
func (o *UpdateConfigBadRequest) WithPayload(payload *models.AppError) *UpdateConfigBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update config bad request response
func (o *UpdateConfigBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConfigUnauthorizedCode is the HTTP code returned for type UpdateConfigUnauthorized
const UpdateConfigUnauthorizedCode int = 401

// UpdateConfigUnauthorized Authorization token is missing or invalid.
//
// swagger:response updateConfigUnauthorized
type UpdateConfigUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewUpdateConfigUnauthorized creates UpdateConfigUnauthorized with default headers values
func NewUpdateConfigUnauthorized() *UpdateConfigUnauthorized {

	return &UpdateConfigUnauthorized{}
}

// WithPayload adds the payload to the update config unauthorized response
func (o *UpdateConfigUnauthorized) WithPayload(payload *models.AppError) *UpdateConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update config unauthorized response
func (o *UpdateConfigUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConfigNotFoundCode is the HTTP code returned for type UpdateConfigNotFound
const UpdateConfigNotFoundCode int = 404

// UpdateConfigNotFound Configuration was not found.
//
// swagger:response updateConfigNotFound
type UpdateConfigNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewUpdateConfigNotFound creates UpdateConfigNotFound with default headers values
func NewUpdateConfigNotFound() *UpdateConfigNotFound {

	return &UpdateConfigNotFound{}
}

// WithPayload adds the payload to the update config not found response
func (o *UpdateConfigNotFound) WithPayload(payload *models.AppError) *UpdateConfigNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update config not found response
func (o *UpdateConfigNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateConfigInternalServerErrorCode is the HTTP code returned for type UpdateConfigInternalServerError
const UpdateConfigInternalServerErrorCode int = 500

// UpdateConfigInternalServerError Configuration could not be updated.
//
// swagger:response updateConfigInternalServerError
type UpdateConfigInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewUpdateConfigInternalServerError creates UpdateConfigInternalServerError with default headers values
func NewUpdateConfigInternalServerError() *UpdateConfigInternalServerError {

	return &UpdateConfigInternalServerError{}
}

// WithPayload adds the payload to the update config internal server error response
func (o *UpdateConfigInternalServerError) WithPayload(payload *models.AppError) *UpdateConfigInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update config internal server error response
func (o *UpdateConfigInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
