// Code generated by go-swagger; DO NOT EDIT.

package configs

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateConfigHandlerFunc turns a function with the right signature into a update config handler
type UpdateConfigHandlerFunc func(UpdateConfigParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateConfigHandlerFunc) Handle(params UpdateConfigParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// UpdateConfigHandler interface for that can handle valid update config params
type UpdateConfigHandler interface {
	Handle(UpdateConfigParams, any) middleware.Responder
}

// NewUpdateConfig creates a new http.Handler for the update config operation
func NewUpdateConfig(ctx *middleware.Context, handler UpdateConfigHandler) *UpdateConfig {
	return &UpdateConfig{Context: ctx, Handler: handler}
}

// UpdateConfig swagger:route PATCH /api/configs/{config} configs updateConfig
//
// Applies a merge patch to a satellite configuration.
type UpdateConfig struct {
	Context *middleware.Context
	Handler UpdateConfigHandler
}

func (o *UpdateConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewUpdateConfigParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
