name: Publish and Sign Snapshot Image
description: Publishes and signs a snapshot image using Task and docker buildx.

inputs:
  IMAGE_TAGS:
    description: 'Tags for the image, e.g. "latest, v1.0.0"'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  REGISTRY_PASSWORD:
    description: 'Registry password'
    required: true
  REGISTRY_ADDRESS:
    description: 'Registry address'
    required: true
  REGISTRY_USERNAME:
    description: 'Registry username'
    required: true
  PROJECT_NAME:
    description: 'Project Name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24.11"

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0

    - name: Check Env Variables
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: cosign env

    - name: Publish and Sign Both Components
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REGISTRY: ${{ inputs.REGISTRY_ADDRESS }}
        REG_USER: ${{ inputs.REGISTRY_USERNAME }}
        REG_PASS: ${{ inputs.REGISTRY_PASSWORD }}
        PROJECT: ${{ inputs.PROJECT_NAME }}
        TAG: ${{ inputs.IMAGE_TAGS }}
      run: task publish-and-sign
