// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// DeleteSatelliteOKCode is the HTTP code returned for type DeleteSatelliteOK
const DeleteSatelliteOKCode int = 200

// DeleteSatelliteOK Satellite deleted.
//
// swagger:response deleteSatelliteOK
type DeleteSatelliteOK struct {

	// In: Body
	Payload models.APIEmptyObject `json:"body,omitempty"`
}

// NewDeleteSatelliteOK creates DeleteSatelliteOK with default headers values
func NewDeleteSatelliteOK() *DeleteSatelliteOK {

	return &DeleteSatelliteOK{}
}

// WithPayload adds the payload to the delete satellite o k response
func (o *DeleteSatelliteOK) WithPayload(payload models.APIEmptyObject) *DeleteSatelliteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete satellite o k response
func (o *DeleteSatelliteOK) SetPayload(payload models.APIEmptyObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSatelliteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteSatelliteBadRequestCode is the HTTP code returned for type DeleteSatelliteBadRequest
const DeleteSatelliteBadRequestCode int = 400

// DeleteSatelliteBadRequest Satellite does not exist or cannot be deleted.
//
// swagger:response deleteSatelliteBadRequest
type DeleteSatelliteBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewDeleteSatelliteBadRequest creates DeleteSatelliteBadRequest with default headers values
func NewDeleteSatelliteBadRequest() *DeleteSatelliteBadRequest {

	return &DeleteSatelliteBadRequest{}
}

// WithPayload adds the payload to the delete satellite bad request response
func (o *DeleteSatelliteBadRequest) WithPayload(payload *models.AppError) *DeleteSatelliteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete satellite bad request response
func (o *DeleteSatelliteBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSatelliteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSatelliteUnauthorizedCode is the HTTP code returned for type DeleteSatelliteUnauthorized
const DeleteSatelliteUnauthorizedCode int = 401

// DeleteSatelliteUnauthorized Authorization token is missing or invalid.
//
// swagger:response deleteSatelliteUnauthorized
type DeleteSatelliteUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewDeleteSatelliteUnauthorized creates DeleteSatelliteUnauthorized with default headers values
func NewDeleteSatelliteUnauthorized() *DeleteSatelliteUnauthorized {

	return &DeleteSatelliteUnauthorized{}
}

// WithPayload adds the payload to the delete satellite unauthorized response
func (o *DeleteSatelliteUnauthorized) WithPayload(payload *models.AppError) *DeleteSatelliteUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete satellite unauthorized response
func (o *DeleteSatelliteUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSatelliteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteSatelliteInternalServerErrorCode is the HTTP code returned for type DeleteSatelliteInternalServerError
const DeleteSatelliteInternalServerErrorCode int = 500

// DeleteSatelliteInternalServerError Satellite could not be deleted.
//
// swagger:response deleteSatelliteInternalServerError
type DeleteSatelliteInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewDeleteSatelliteInternalServerError creates DeleteSatelliteInternalServerError with default headers values
func NewDeleteSatelliteInternalServerError() *DeleteSatelliteInternalServerError {

	return &DeleteSatelliteInternalServerError{}
}

// WithPayload adds the payload to the delete satellite internal server error response
func (o *DeleteSatelliteInternalServerError) WithPayload(payload *models.AppError) *DeleteSatelliteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete satellite internal server error response
func (o *DeleteSatelliteInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteSatelliteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
