// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSatelliteHandlerFunc turns a function with the right signature into a delete satellite handler
type DeleteSatelliteHandlerFunc func(DeleteSatelliteParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSatelliteHandlerFunc) Handle(params DeleteSatelliteParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// DeleteSatelliteHandler interface for that can handle valid delete satellite params
type DeleteSatelliteHandler interface {
	Handle(DeleteSatelliteParams, any) middleware.Responder
}

// NewDeleteSatellite creates a new http.Handler for the delete satellite operation
func NewDeleteSatellite(ctx *middleware.Context, handler DeleteSatelliteHandler) *DeleteSatellite {
	return &DeleteSatellite{Context: ctx, Handler: handler}
}

// DeleteSatellite swagger:route DELETE /api/satellites/{satellite} satellites deleteSatellite
//
// Deletes a satellite.
type DeleteSatellite struct {
	Context *middleware.Context
	Handler DeleteSatelliteHandler
}

func (o *DeleteSatellite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewDeleteSatelliteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
