// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCachedImagesHandlerFunc turns a function with the right signature into a get cached images handler
type GetCachedImagesHandlerFunc func(GetCachedImagesParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCachedImagesHandlerFunc) Handle(params GetCachedImagesParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetCachedImagesHandler interface for that can handle valid get cached images params
type GetCachedImagesHandler interface {
	Handle(GetCachedImagesParams, any) middleware.Responder
}

// NewGetCachedImages creates a new http.Handler for the get cached images operation
func NewGetCachedImages(ctx *middleware.Context, handler GetCachedImagesHandler) *GetCachedImages {
	return &GetCachedImages{Context: ctx, Handler: handler}
}

// GetCachedImages swagger:route GET /api/satellites/{satellite}/images satellites getCachedImages
//
// Lists the latest cached images reported by a satellite.
type GetCachedImages struct {
	Context *middleware.Context
	Handler GetCachedImagesHandler
}

func (o *GetCachedImages) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetCachedImagesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
