// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSatelliteStatusHandlerFunc turns a function with the right signature into a get satellite status handler
type GetSatelliteStatusHandlerFunc func(GetSatelliteStatusParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSatelliteStatusHandlerFunc) Handle(params GetSatelliteStatusParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetSatelliteStatusHandler interface for that can handle valid get satellite status params
type GetSatelliteStatusHandler interface {
	Handle(GetSatelliteStatusParams, any) middleware.Responder
}

// NewGetSatelliteStatus creates a new http.Handler for the get satellite status operation
func NewGetSatelliteStatus(ctx *middleware.Context, handler GetSatelliteStatusHandler) *GetSatelliteStatus {
	return &GetSatelliteStatus{Context: ctx, Handler: handler}
}

// GetSatelliteStatus swagger:route GET /api/satellites/{satellite}/status satellites getSatelliteStatus
//
// Gets the latest satellite status report.
type GetSatelliteStatus struct {
	Context *middleware.Context
	Handler GetSatelliteStatusHandler
}

func (o *GetSatelliteStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetSatelliteStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
