// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// GetSatelliteStatusOKCode is the HTTP code returned for type GetSatelliteStatusOK
const GetSatelliteStatusOKCode int = 200

// GetSatelliteStatusOK Latest satellite status returned.
//
// swagger:response getSatelliteStatusOK
type GetSatelliteStatusOK struct {

	// In: Body
	Payload *models.APISatelliteStatus `json:"body,omitempty"`
}

// NewGetSatelliteStatusOK creates GetSatelliteStatusOK with default headers values
func NewGetSatelliteStatusOK() *GetSatelliteStatusOK {

	return &GetSatelliteStatusOK{}
}

// WithPayload adds the payload to the get satellite status o k response
func (o *GetSatelliteStatusOK) WithPayload(payload *models.APISatelliteStatus) *GetSatelliteStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite status o k response
func (o *GetSatelliteStatusOK) SetPayload(payload *models.APISatelliteStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSatelliteStatusUnauthorizedCode is the HTTP code returned for type GetSatelliteStatusUnauthorized
const GetSatelliteStatusUnauthorizedCode int = 401

// GetSatelliteStatusUnauthorized Authorization token is missing or invalid.
//
// swagger:response getSatelliteStatusUnauthorized
type GetSatelliteStatusUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSatelliteStatusUnauthorized creates GetSatelliteStatusUnauthorized with default headers values
func NewGetSatelliteStatusUnauthorized() *GetSatelliteStatusUnauthorized {

	return &GetSatelliteStatusUnauthorized{}
}

// WithPayload adds the payload to the get satellite status unauthorized response
func (o *GetSatelliteStatusUnauthorized) WithPayload(payload *models.AppError) *GetSatelliteStatusUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite status unauthorized response
func (o *GetSatelliteStatusUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSatelliteStatusNotFoundCode is the HTTP code returned for type GetSatelliteStatusNotFound
const GetSatelliteStatusNotFoundCode int = 404

// GetSatelliteStatusNotFound Satellite or status report was not found.
//
// swagger:response getSatelliteStatusNotFound
type GetSatelliteStatusNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSatelliteStatusNotFound creates GetSatelliteStatusNotFound with default headers values
func NewGetSatelliteStatusNotFound() *GetSatelliteStatusNotFound {

	return &GetSatelliteStatusNotFound{}
}

// WithPayload adds the payload to the get satellite status not found response
func (o *GetSatelliteStatusNotFound) WithPayload(payload *models.AppError) *GetSatelliteStatusNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite status not found response
func (o *GetSatelliteStatusNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSatelliteStatusInternalServerErrorCode is the HTTP code returned for type GetSatelliteStatusInternalServerError
const GetSatelliteStatusInternalServerErrorCode int = 500

// GetSatelliteStatusInternalServerError Satellite status could not be loaded.
//
// swagger:response getSatelliteStatusInternalServerError
type GetSatelliteStatusInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSatelliteStatusInternalServerError creates GetSatelliteStatusInternalServerError with default headers values
func NewGetSatelliteStatusInternalServerError() *GetSatelliteStatusInternalServerError {

	return &GetSatelliteStatusInternalServerError{}
}

// WithPayload adds the payload to the get satellite status internal server error response
func (o *GetSatelliteStatusInternalServerError) WithPayload(payload *models.AppError) *GetSatelliteStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite status internal server error response
func (o *GetSatelliteStatusInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
