// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSatelliteHandlerFunc turns a function with the right signature into a get satellite handler
type GetSatelliteHandlerFunc func(GetSatelliteParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSatelliteHandlerFunc) Handle(params GetSatelliteParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetSatelliteHandler interface for that can handle valid get satellite params
type GetSatelliteHandler interface {
	Handle(GetSatelliteParams, any) middleware.Responder
}

// NewGetSatellite creates a new http.Handler for the get satellite operation
func NewGetSatellite(ctx *middleware.Context, handler GetSatelliteHandler) *GetSatellite {
	return &GetSatellite{Context: ctx, Handler: handler}
}

// GetSatellite swagger:route GET /api/satellites/{satellite} satellites getSatellite
//
// Gets a satellite by name.
type GetSatellite struct {
	Context *middleware.Context
	Handler GetSatelliteHandler
}

func (o *GetSatellite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetSatelliteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
