// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// GetSatelliteOKCode is the HTTP code returned for type GetSatelliteOK
const GetSatelliteOKCode int = 200

// GetSatelliteOK Satellite returned.
//
// swagger:response getSatelliteOK
type GetSatelliteOK struct {

	// In: Body
	Payload *models.APISatellite `json:"body,omitempty"`
}

// NewGetSatelliteOK creates GetSatelliteOK with default headers values
func NewGetSatelliteOK() *GetSatelliteOK {

	return &GetSatelliteOK{}
}

// WithPayload adds the payload to the get satellite o k response
func (o *GetSatelliteOK) WithPayload(payload *models.APISatellite) *GetSatelliteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite o k response
func (o *GetSatelliteOK) SetPayload(payload *models.APISatellite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSatelliteUnauthorizedCode is the HTTP code returned for type GetSatelliteUnauthorized
const GetSatelliteUnauthorizedCode int = 401

// GetSatelliteUnauthorized Authorization token is missing or invalid.
//
// swagger:response getSatelliteUnauthorized
type GetSatelliteUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSatelliteUnauthorized creates GetSatelliteUnauthorized with default headers values
func NewGetSatelliteUnauthorized() *GetSatelliteUnauthorized {

	return &GetSatelliteUnauthorized{}
}

// WithPayload adds the payload to the get satellite unauthorized response
func (o *GetSatelliteUnauthorized) WithPayload(payload *models.AppError) *GetSatelliteUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite unauthorized response
func (o *GetSatelliteUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSatelliteInternalServerErrorCode is the HTTP code returned for type GetSatelliteInternalServerError
const GetSatelliteInternalServerErrorCode int = 500

// GetSatelliteInternalServerError Satellite could not be loaded.
//
// swagger:response getSatelliteInternalServerError
type GetSatelliteInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSatelliteInternalServerError creates GetSatelliteInternalServerError with default headers values
func NewGetSatelliteInternalServerError() *GetSatelliteInternalServerError {

	return &GetSatelliteInternalServerError{}
}

// WithPayload adds the payload to the get satellite internal server error response
func (o *GetSatelliteInternalServerError) WithPayload(payload *models.AppError) *GetSatelliteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get satellite internal server error response
func (o *GetSatelliteInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSatelliteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
