// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListSatellitesHandlerFunc turns a function with the right signature into a list satellites handler
type ListSatellitesHandlerFunc func(ListSatellitesParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn ListSatellitesHandlerFunc) Handle(params ListSatellitesParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// ListSatellitesHandler interface for that can handle valid list satellites params
type ListSatellitesHandler interface {
	Handle(ListSatellitesParams, any) middleware.Responder
}

// NewListSatellites creates a new http.Handler for the list satellites operation
func NewListSatellites(ctx *middleware.Context, handler ListSatellitesHandler) *ListSatellites {
	return &ListSatellites{Context: ctx, Handler: handler}
}

// ListSatellites swagger:route GET /api/satellites satellites listSatellites
//
// Lists satellites.
type ListSatellites struct {
	Context *middleware.Context
	Handler ListSatellitesHandler
}

func (o *ListSatellites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewListSatellitesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
