// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ListActiveSatellitesOKCode is the HTTP code returned for type ListActiveSatellitesOK
const ListActiveSatellitesOKCode int = 200

// ListActiveSatellitesOK Active satellites returned.
//
// swagger:response listActiveSatellitesOK
type ListActiveSatellitesOK struct {

	// In: Body
	Payload []*models.APIActiveSatellite `json:"body,omitempty"`
}

// NewListActiveSatellitesOK creates ListActiveSatellitesOK with default headers values
func NewListActiveSatellitesOK() *ListActiveSatellitesOK {

	return &ListActiveSatellitesOK{}
}

// WithPayload adds the payload to the list active satellites o k response
func (o *ListActiveSatellitesOK) WithPayload(payload []*models.APIActiveSatellite) *ListActiveSatellitesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list active satellites o k response
func (o *ListActiveSatellitesOK) SetPayload(payload []*models.APIActiveSatellite) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListActiveSatellitesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.APIActiveSatellite, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListActiveSatellitesUnauthorizedCode is the HTTP code returned for type ListActiveSatellitesUnauthorized
const ListActiveSatellitesUnauthorizedCode int = 401

// ListActiveSatellitesUnauthorized Authorization token is missing or invalid.
//
// swagger:response listActiveSatellitesUnauthorized
type ListActiveSatellitesUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListActiveSatellitesUnauthorized creates ListActiveSatellitesUnauthorized with default headers values
func NewListActiveSatellitesUnauthorized() *ListActiveSatellitesUnauthorized {

	return &ListActiveSatellitesUnauthorized{}
}

// WithPayload adds the payload to the list active satellites unauthorized response
func (o *ListActiveSatellitesUnauthorized) WithPayload(payload *models.AppError) *ListActiveSatellitesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list active satellites unauthorized response
func (o *ListActiveSatellitesUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListActiveSatellitesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListActiveSatellitesInternalServerErrorCode is the HTTP code returned for type ListActiveSatellitesInternalServerError
const ListActiveSatellitesInternalServerErrorCode int = 500

// ListActiveSatellitesInternalServerError Active satellites could not be listed.
//
// swagger:response listActiveSatellitesInternalServerError
type ListActiveSatellitesInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListActiveSatellitesInternalServerError creates ListActiveSatellitesInternalServerError with default headers values
func NewListActiveSatellitesInternalServerError() *ListActiveSatellitesInternalServerError {

	return &ListActiveSatellitesInternalServerError{}
}

// WithPayload adds the payload to the list active satellites internal server error response
func (o *ListActiveSatellitesInternalServerError) WithPayload(payload *models.AppError) *ListActiveSatellitesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list active satellites internal server error response
func (o *ListActiveSatellitesInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListActiveSatellitesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
