// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListStaleSatellitesHandlerFunc turns a function with the right signature into a list stale satellites handler
type ListStaleSatellitesHandlerFunc func(ListStaleSatellitesParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn ListStaleSatellitesHandlerFunc) Handle(params ListStaleSatellitesParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// ListStaleSatellitesHandler interface for that can handle valid list stale satellites params
type ListStaleSatellitesHandler interface {
	Handle(ListStaleSatellitesParams, any) middleware.Responder
}

// NewListStaleSatellites creates a new http.Handler for the list stale satellites operation
func NewListStaleSatellites(ctx *middleware.Context, handler ListStaleSatellitesHandler) *ListStaleSatellites {
	return &ListStaleSatellites{Context: ctx, Handler: handler}
}

// ListStaleSatellites swagger:route GET /api/satellites/stale satellites listStaleSatellites
//
// Lists stale satellites.
type ListStaleSatellites struct {
	Context *middleware.Context
	Handler ListStaleSatellitesHandler
}

func (o *ListStaleSatellites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewListStaleSatellitesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
