// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListActiveSatellitesHandlerFunc turns a function with the right signature into a list active satellites handler
type ListActiveSatellitesHandlerFunc func(ListActiveSatellitesParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn ListActiveSatellitesHandlerFunc) Handle(params ListActiveSatellitesParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// ListActiveSatellitesHandler interface for that can handle valid list active satellites params
type ListActiveSatellitesHandler interface {
	Handle(ListActiveSatellitesParams, any) middleware.Responder
}

// NewListActiveSatellites creates a new http.Handler for the list active satellites operation
func NewListActiveSatellites(ctx *middleware.Context, handler ListActiveSatellitesHandler) *ListActiveSatellites {
	return &ListActiveSatellites{Context: ctx, Handler: handler}
}

// ListActiveSatellites swagger:route GET /api/satellites/active satellites listActiveSatellites
//
// Lists active satellites.
type ListActiveSatellites struct {
	Context *middleware.Context
	Handler ListActiveSatellitesHandler
}

func (o *ListActiveSatellites) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewListActiveSatellitesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
