// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RegisterSatelliteHandlerFunc turns a function with the right signature into a register satellite handler
type RegisterSatelliteHandlerFunc func(RegisterSatelliteParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterSatelliteHandlerFunc) Handle(params RegisterSatelliteParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// RegisterSatelliteHandler interface for that can handle valid register satellite params
type RegisterSatelliteHandler interface {
	Handle(RegisterSatelliteParams, any) middleware.Responder
}

// NewRegisterSatellite creates a new http.Handler for the register satellite operation
func NewRegisterSatellite(ctx *middleware.Context, handler RegisterSatelliteHandler) *RegisterSatellite {
	return &RegisterSatellite{Context: ctx, Handler: handler}
}

// RegisterSatellite swagger:route POST /api/satellites satellites registerSatellite
//
// Registers a token-managed satellite.
type RegisterSatellite struct {
	Context *middleware.Context
	Handler RegisterSatelliteHandler
}

func (o *RegisterSatellite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewRegisterSatelliteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
