// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// RegisterSatelliteOKCode is the HTTP code returned for type RegisterSatelliteOK
const RegisterSatelliteOKCode int = 200

// RegisterSatelliteOK Satellite registered with a zero-touch token.
//
// swagger:response registerSatelliteOK
type RegisterSatelliteOK struct {

	// In: Body
	Payload *models.RegisterSatelliteResponse `json:"body,omitempty"`
}

// NewRegisterSatelliteOK creates RegisterSatelliteOK with default headers values
func NewRegisterSatelliteOK() *RegisterSatelliteOK {

	return &RegisterSatelliteOK{}
}

// WithPayload adds the payload to the register satellite o k response
func (o *RegisterSatelliteOK) WithPayload(payload *models.RegisterSatelliteResponse) *RegisterSatelliteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite o k response
func (o *RegisterSatelliteOK) SetPayload(payload *models.RegisterSatelliteResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteBadRequestCode is the HTTP code returned for type RegisterSatelliteBadRequest
const RegisterSatelliteBadRequestCode int = 400

// RegisterSatelliteBadRequest Registration payload, name, config, or robot account is invalid.
//
// swagger:response registerSatelliteBadRequest
type RegisterSatelliteBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteBadRequest creates RegisterSatelliteBadRequest with default headers values
func NewRegisterSatelliteBadRequest() *RegisterSatelliteBadRequest {

	return &RegisterSatelliteBadRequest{}
}

// WithPayload adds the payload to the register satellite bad request response
func (o *RegisterSatelliteBadRequest) WithPayload(payload *models.AppError) *RegisterSatelliteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite bad request response
func (o *RegisterSatelliteBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteUnauthorizedCode is the HTTP code returned for type RegisterSatelliteUnauthorized
const RegisterSatelliteUnauthorizedCode int = 401

// RegisterSatelliteUnauthorized Authorization token is missing or invalid.
//
// swagger:response registerSatelliteUnauthorized
type RegisterSatelliteUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteUnauthorized creates RegisterSatelliteUnauthorized with default headers values
func NewRegisterSatelliteUnauthorized() *RegisterSatelliteUnauthorized {

	return &RegisterSatelliteUnauthorized{}
}

// WithPayload adds the payload to the register satellite unauthorized response
func (o *RegisterSatelliteUnauthorized) WithPayload(payload *models.AppError) *RegisterSatelliteUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite unauthorized response
func (o *RegisterSatelliteUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteInternalServerErrorCode is the HTTP code returned for type RegisterSatelliteInternalServerError
const RegisterSatelliteInternalServerErrorCode int = 500

// RegisterSatelliteInternalServerError Satellite could not be registered.
//
// swagger:response registerSatelliteInternalServerError
type RegisterSatelliteInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteInternalServerError creates RegisterSatelliteInternalServerError with default headers values
func NewRegisterSatelliteInternalServerError() *RegisterSatelliteInternalServerError {

	return &RegisterSatelliteInternalServerError{}
}

// WithPayload adds the payload to the register satellite internal server error response
func (o *RegisterSatelliteInternalServerError) WithPayload(payload *models.AppError) *RegisterSatelliteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite internal server error response
func (o *RegisterSatelliteInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
