// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// SpiffeZtrOKCode is the HTTP code returned for type SpiffeZtrOK
const SpiffeZtrOKCode int = 200

// SpiffeZtrOK SPIFFE zero-touch registration completed and registry credentials returned.
//
// swagger:response spiffeZtrOK
type SpiffeZtrOK struct {

	// In: Body
	Payload *models.APIStateConfig `json:"body,omitempty"`
}

// NewSpiffeZtrOK creates SpiffeZtrOK with default headers values
func NewSpiffeZtrOK() *SpiffeZtrOK {

	return &SpiffeZtrOK{}
}

// WithPayload adds the payload to the spiffe ztr o k response
func (o *SpiffeZtrOK) WithPayload(payload *models.APIStateConfig) *SpiffeZtrOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the spiffe ztr o k response
func (o *SpiffeZtrOK) SetPayload(payload *models.APIStateConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SpiffeZtrOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SpiffeZtrBadRequestCode is the HTTP code returned for type SpiffeZtrBadRequest
const SpiffeZtrBadRequestCode int = 400

// SpiffeZtrBadRequest SPIFFE ID format or satellite identity is invalid.
//
// swagger:response spiffeZtrBadRequest
type SpiffeZtrBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSpiffeZtrBadRequest creates SpiffeZtrBadRequest with default headers values
func NewSpiffeZtrBadRequest() *SpiffeZtrBadRequest {

	return &SpiffeZtrBadRequest{}
}

// WithPayload adds the payload to the spiffe ztr bad request response
func (o *SpiffeZtrBadRequest) WithPayload(payload *models.AppError) *SpiffeZtrBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the spiffe ztr bad request response
func (o *SpiffeZtrBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SpiffeZtrBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SpiffeZtrUnauthorizedCode is the HTTP code returned for type SpiffeZtrUnauthorized
const SpiffeZtrUnauthorizedCode int = 401

// SpiffeZtrUnauthorized SPIFFE authentication is missing or invalid.
//
// swagger:response spiffeZtrUnauthorized
type SpiffeZtrUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSpiffeZtrUnauthorized creates SpiffeZtrUnauthorized with default headers values
func NewSpiffeZtrUnauthorized() *SpiffeZtrUnauthorized {

	return &SpiffeZtrUnauthorized{}
}

// WithPayload adds the payload to the spiffe ztr unauthorized response
func (o *SpiffeZtrUnauthorized) WithPayload(payload *models.AppError) *SpiffeZtrUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the spiffe ztr unauthorized response
func (o *SpiffeZtrUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SpiffeZtrUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SpiffeZtrTooManyRequestsCode is the HTTP code returned for type SpiffeZtrTooManyRequests
const SpiffeZtrTooManyRequestsCode int = 429

// SpiffeZtrTooManyRequests Too many SPIFFE zero-touch registration attempts.
//
// swagger:response spiffeZtrTooManyRequests
type SpiffeZtrTooManyRequests struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSpiffeZtrTooManyRequests creates SpiffeZtrTooManyRequests with default headers values
func NewSpiffeZtrTooManyRequests() *SpiffeZtrTooManyRequests {

	return &SpiffeZtrTooManyRequests{}
}

// WithPayload adds the payload to the spiffe ztr too many requests response
func (o *SpiffeZtrTooManyRequests) WithPayload(payload *models.AppError) *SpiffeZtrTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the spiffe ztr too many requests response
func (o *SpiffeZtrTooManyRequests) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SpiffeZtrTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SpiffeZtrInternalServerErrorCode is the HTTP code returned for type SpiffeZtrInternalServerError
const SpiffeZtrInternalServerErrorCode int = 500

// SpiffeZtrInternalServerError SPIFFE zero-touch registration could not be completed.
//
// swagger:response spiffeZtrInternalServerError
type SpiffeZtrInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSpiffeZtrInternalServerError creates SpiffeZtrInternalServerError with default headers values
func NewSpiffeZtrInternalServerError() *SpiffeZtrInternalServerError {

	return &SpiffeZtrInternalServerError{}
}

// WithPayload adds the payload to the spiffe ztr internal server error response
func (o *SpiffeZtrInternalServerError) WithPayload(payload *models.AppError) *SpiffeZtrInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the spiffe ztr internal server error response
func (o *SpiffeZtrInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SpiffeZtrInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
