// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// SyncSatelliteOKCode is the HTTP code returned for type SyncSatelliteOK
const SyncSatelliteOKCode int = 200

// SyncSatelliteOK Satellite status report accepted.
//
// swagger:response syncSatelliteOK
type SyncSatelliteOK struct {
}

// NewSyncSatelliteOK creates SyncSatelliteOK with default headers values
func NewSyncSatelliteOK() *SyncSatelliteOK {

	return &SyncSatelliteOK{}
}

// WriteResponse to the client
func (o *SyncSatelliteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SyncSatelliteBadRequestCode is the HTTP code returned for type SyncSatelliteBadRequest
const SyncSatelliteBadRequestCode int = 400

// SyncSatelliteBadRequest Status payload or heartbeat interval is invalid.
//
// swagger:response syncSatelliteBadRequest
type SyncSatelliteBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSyncSatelliteBadRequest creates SyncSatelliteBadRequest with default headers values
func NewSyncSatelliteBadRequest() *SyncSatelliteBadRequest {

	return &SyncSatelliteBadRequest{}
}

// WithPayload adds the payload to the sync satellite bad request response
func (o *SyncSatelliteBadRequest) WithPayload(payload *models.AppError) *SyncSatelliteBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sync satellite bad request response
func (o *SyncSatelliteBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SyncSatelliteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SyncSatelliteForbiddenCode is the HTTP code returned for type SyncSatelliteForbidden
const SyncSatelliteForbiddenCode int = 403

// SyncSatelliteForbidden Satellite identity is unknown or not authorized.
//
// swagger:response syncSatelliteForbidden
type SyncSatelliteForbidden struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSyncSatelliteForbidden creates SyncSatelliteForbidden with default headers values
func NewSyncSatelliteForbidden() *SyncSatelliteForbidden {

	return &SyncSatelliteForbidden{}
}

// WithPayload adds the payload to the sync satellite forbidden response
func (o *SyncSatelliteForbidden) WithPayload(payload *models.AppError) *SyncSatelliteForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sync satellite forbidden response
func (o *SyncSatelliteForbidden) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SyncSatelliteForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SyncSatelliteInternalServerErrorCode is the HTTP code returned for type SyncSatelliteInternalServerError
const SyncSatelliteInternalServerErrorCode int = 500

// SyncSatelliteInternalServerError Satellite status report could not be saved.
//
// swagger:response syncSatelliteInternalServerError
type SyncSatelliteInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewSyncSatelliteInternalServerError creates SyncSatelliteInternalServerError with default headers values
func NewSyncSatelliteInternalServerError() *SyncSatelliteInternalServerError {

	return &SyncSatelliteInternalServerError{}
}

// WithPayload adds the payload to the sync satellite internal server error response
func (o *SyncSatelliteInternalServerError) WithPayload(payload *models.AppError) *SyncSatelliteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sync satellite internal server error response
func (o *SyncSatelliteInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SyncSatelliteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
