// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SyncSatelliteHandlerFunc turns a function with the right signature into a sync satellite handler
type SyncSatelliteHandlerFunc func(SyncSatelliteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SyncSatelliteHandlerFunc) Handle(params SyncSatelliteParams) middleware.Responder {
	return fn(params)
}

// SyncSatelliteHandler interface for that can handle valid sync satellite params
type SyncSatelliteHandler interface {
	Handle(SyncSatelliteParams) middleware.Responder
}

// NewSyncSatellite creates a new http.Handler for the sync satellite operation
func NewSyncSatellite(ctx *middleware.Context, handler SyncSatelliteHandler) *SyncSatellite {
	return &SyncSatellite{Context: ctx, Handler: handler}
}

// SyncSatellite swagger:route POST /satellites/sync satellites syncSatellite
//
// Reports satellite status.
type SyncSatellite struct {
	Context *middleware.Context
	Handler SyncSatelliteHandler
}

func (o *SyncSatellite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewSyncSatelliteParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
