// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ZtrHandlerFunc turns a function with the right signature into a ztr handler
type ZtrHandlerFunc func(ZtrParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ZtrHandlerFunc) Handle(params ZtrParams) middleware.Responder {
	return fn(params)
}

// ZtrHandler interface for that can handle valid ztr params
type ZtrHandler interface {
	Handle(ZtrParams) middleware.Responder
}

// NewZtr creates a new http.Handler for the ztr operation
func NewZtr(ctx *middleware.Context, handler ZtrHandler) *Ztr {
	return &Ztr{Context: ctx, Handler: handler}
}

// Ztr swagger:route GET /satellites/ztr/{token} satellites ztr
//
// Performs token-based zero-touch registration.
type Ztr struct {
	Context *middleware.Context
	Handler ZtrHandler
}

func (o *Ztr) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewZtrParams()
	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
