// Code generated by go-swagger; DO NOT EDIT.

package satellites

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ZtrOKCode is the HTTP code returned for type ZtrOK
const ZtrOKCode int = 200

// ZtrOK Zero-touch registration completed and registry credentials returned.
//
// swagger:response ztrOK
type ZtrOK struct {

	// In: Body
	Payload *models.APIStateConfig `json:"body,omitempty"`
}

// NewZtrOK creates ZtrOK with default headers values
func NewZtrOK() *ZtrOK {

	return &ZtrOK{}
}

// WithPayload adds the payload to the ztr o k response
func (o *ZtrOK) WithPayload(payload *models.APIStateConfig) *ZtrOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ztr o k response
func (o *ZtrOK) SetPayload(payload *models.APIStateConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZtrOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ZtrBadRequestCode is the HTTP code returned for type ZtrBadRequest
const ZtrBadRequestCode int = 400

// ZtrBadRequest Registration token is invalid.
//
// swagger:response ztrBadRequest
type ZtrBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewZtrBadRequest creates ZtrBadRequest with default headers values
func NewZtrBadRequest() *ZtrBadRequest {

	return &ZtrBadRequest{}
}

// WithPayload adds the payload to the ztr bad request response
func (o *ZtrBadRequest) WithPayload(payload *models.AppError) *ZtrBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ztr bad request response
func (o *ZtrBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZtrBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ZtrUnauthorizedCode is the HTTP code returned for type ZtrUnauthorized
const ZtrUnauthorizedCode int = 401

// ZtrUnauthorized Registration token has expired.
//
// swagger:response ztrUnauthorized
type ZtrUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewZtrUnauthorized creates ZtrUnauthorized with default headers values
func NewZtrUnauthorized() *ZtrUnauthorized {

	return &ZtrUnauthorized{}
}

// WithPayload adds the payload to the ztr unauthorized response
func (o *ZtrUnauthorized) WithPayload(payload *models.AppError) *ZtrUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ztr unauthorized response
func (o *ZtrUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZtrUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ZtrTooManyRequestsCode is the HTTP code returned for type ZtrTooManyRequests
const ZtrTooManyRequestsCode int = 429

// ZtrTooManyRequests Too many zero-touch registration attempts.
//
// swagger:response ztrTooManyRequests
type ZtrTooManyRequests struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewZtrTooManyRequests creates ZtrTooManyRequests with default headers values
func NewZtrTooManyRequests() *ZtrTooManyRequests {

	return &ZtrTooManyRequests{}
}

// WithPayload adds the payload to the ztr too many requests response
func (o *ZtrTooManyRequests) WithPayload(payload *models.AppError) *ZtrTooManyRequests {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ztr too many requests response
func (o *ZtrTooManyRequests) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZtrTooManyRequests) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(429)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ZtrInternalServerErrorCode is the HTTP code returned for type ZtrInternalServerError
const ZtrInternalServerErrorCode int = 500

// ZtrInternalServerError Zero-touch registration could not be completed.
//
// swagger:response ztrInternalServerError
type ZtrInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewZtrInternalServerError creates ZtrInternalServerError with default headers values
func NewZtrInternalServerError() *ZtrInternalServerError {

	return &ZtrInternalServerError{}
}

// WithPayload adds the payload to the ztr internal server error response
func (o *ZtrInternalServerError) WithPayload(payload *models.AppError) *ZtrInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the ztr internal server error response
func (o *ZtrInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ZtrInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
