apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ground-control.fullname" . }}
  labels:
    {{- include "ground-control.labels" . | nindent 4 }}
type: Opaque
stringData:
  HARBOR_URL: {{ .Values.harbor.url | quote }}
  HARBOR_USERNAME: {{ .Values.harbor.username | quote }}
  {{- if not .Values.harbor.existingSecret }}
  HARBOR_PASSWORD: {{ .Values.harbor.password | quote }}
  {{- end }}
  {{- if not .Values.groundControl.existingSecret }}
  ADMIN_PASSWORD: {{ .Values.groundControl.password | quote }}
  {{- end }}
  DB_USERNAME: {{ .Values.database.username | quote }}
  {{- if not .Values.database.existingSecret }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  {{- end }}