//go:build parsec

package parsec

// Signer implements crypto.Signer backed by a hardware-resident PARSEC key.
//
// This is the solution to the Go TLS incompatibility raised in issue #327:
// standard tls.LoadX509KeyPair requires an exportable private key, but PARSEC
// keys are non-exportable by design. By implementing crypto.Signer, we can
// construct a tls.Certificate with PrivateKey set to *Signer, and standard
// Go TLS will call Sign() for all private-key operations — the key material
// never leaves the secure element.
//
// Usage:
//
//	signer, err := NewSigner(client, identityKeyName)
//	cert := tls.Certificate{
//	    Certificate: [][]byte{derCert},
//	    PrivateKey:  signer,
//	}

import (
	"crypto"
	"crypto/x509"
	"fmt"
	"io"

	parsecclient "github.com/parallaxsecond/parsec-client-go/parsec"
	"github.com/parallaxsecond/parsec-client-go/parsec/algorithm"
)

// Signer implements crypto.Signer using a named, hardware-resident PARSEC key.
// The private key material never leaves the secure element.
type Signer struct {
	client  *parsecclient.BasicClient
	keyName string
	pub     crypto.PublicKey
	sigAlg  *algorithm.AsymmetricSignatureAlgorithm
}

// KeyRef is a reference to a hardware-resident PARSEC key by name.
// It satisfies crypto.PrivateKey (which is `any`) so it can be passed to
// crypto.Provider.Sign without changing the existing interface signature.
type KeyRef struct {
	Name string
}

// NewSigner creates a Signer for the given named key.
// It exports the public key from PARSEC to satisfy crypto.Signer.Public().
// The private key material never leaves the hardware.
func NewSigner(client *parsecclient.BasicClient, keyName string) (*Signer, error) {
	pubDER, err := client.PsaExportPublicKey(keyName)
	if err != nil {
		return nil, fmt.Errorf("export public key %q from parsec: %w", keyName, err)
	}

	pub, err := x509.ParsePKIXPublicKey(pubDER)
	if err != nil {
		return nil, fmt.Errorf("parse exported public key: %w", err)
	}

	// ECDSA P-256 with SHA-256. This must match the key attributes used in
	// KeyProvider.ensureIdentityKey(). If the key type changes, update here too.
	sigAlg := algorithm.NewAsymmetricSignature().
		Ecdsa(algorithm.HashAlgorithmTypeSHA256).
		GetAsymmetricSignature()

	return &Signer{
		client:  client,
		keyName: keyName,
		pub:     pub,
		sigAlg:  sigAlg,
	}, nil
}

// Public returns the public key half. Required by crypto.Signer.
func (s *Signer) Public() crypto.PublicKey {
	return s.pub
}

// Sign delegates the signing operation to the PARSEC hardware.
//
// Per the crypto.Signer contract, `digest` is the (already-hashed) input the
// caller wants signed — the Signer must NOT hash again. The rand reader is
// ignored because the hardware generates its own entropy.
//
// This Signer is bound to ECDSA-P256 / SHA-256 (matches the key generated by
// KeyProvider.ensureIdentityKey). The accepted `opts.HashFunc()` values are
// therefore:
//
//   - crypto.SHA256 — the standard Go-TLS case for ECDSA-P256: `digest` is the
//     pre-computed SHA-256 (32 bytes).
//   - crypto.Hash(0) — also accepted, treated as "raw, pre-hashed". The caller
//     promises the bytes are an ECDSA-P256-appropriate digest. We enforce a
//     32-byte length because anything else cannot be a valid SHA-256 digest
//     for this key. Ed25519 raw-signing flows do NOT use this Signer (a
//     separate Ed25519 Signer would be needed if/when an Ed25519 identity key
//     is provisioned).
//
// Any other `opts.HashFunc()` is an algorithm mismatch and is rejected.
//
// (Earlier revisions of this function re-hashed when HashFunc()==0, which
// inverted the convention and produced signatures peers couldn't verify.)
func (s *Signer) Sign(_ io.Reader, digest []byte, opts crypto.SignerOpts) ([]byte, error) {
	if opts != nil {
		if h := opts.HashFunc(); h != crypto.Hash(0) && h != crypto.SHA256 {
			return nil, fmt.Errorf("parsec signer is bound to ECDSA-P256/SHA-256; caller requested %v", h)
		}
	}
	if len(digest) != 32 {
		return nil, fmt.Errorf("parsec signer expects a 32-byte SHA-256 digest, got %d bytes", len(digest))
	}

	sig, err := s.client.PsaSignHash(s.keyName, digest, s.sigAlg)
	if err != nil {
		return nil, fmt.Errorf("parsec sign with key %q: %w", s.keyName, err)
	}
	return sig, nil
}
