// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APIConfigValue APIConfigValue contains a satellite configuration document.
//
// swagger:model APIConfigValue
type APIConfigValue struct {

	// app config
	AppConfig map[string]any `json:"app_config,omitempty"`

	// state config
	StateConfig map[string]any `json:"state_config,omitempty"`

	// zot config
	ZotConfig map[string]any `json:"zot_config,omitempty"`
}

// Validate validates this API config value
func (m *APIConfigValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API config value based on context it is used
func (m *APIConfigValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIConfigValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIConfigValue) UnmarshalBinary(b []byte) error {
	var res APIConfigValue
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
