// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// APIStaleSatellite APIStaleSatellite describes a stale satellite row.
//
// swagger:model APIStaleSatellite
type APIStaleSatellite struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

	// heartbeat interval
	HeartbeatInterval *NullString `json:"HeartbeatInterval,omitempty"`

	// ID
	ID int32 `json:"ID,omitempty"`

	// last seen
	LastSeen *NullTime `json:"LastSeen,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// seconds since seen
	SecondsSinceSeen int64 `json:"SecondsSinceSeen,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *APIStaleSatellite) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

		HeartbeatInterval *NullString `json:"HeartbeatInterval,omitempty"`

		ID int32 `json:"ID,omitempty"`

		LastSeen *NullTime `json:"LastSeen,omitempty"`

		Name string `json:"Name,omitempty"`

		SecondsSinceSeen int64 `json:"SecondsSinceSeen,omitempty"`

		UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`
	}
	if err := jsonutils.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.CreatedAt = dataAO0.CreatedAt

	m.HeartbeatInterval = dataAO0.HeartbeatInterval

	m.ID = dataAO0.ID

	m.LastSeen = dataAO0.LastSeen

	m.Name = dataAO0.Name

	m.SecondsSinceSeen = dataAO0.SecondsSinceSeen

	m.UpdatedAt = dataAO0.UpdatedAt

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m APIStaleSatellite) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

		HeartbeatInterval *NullString `json:"HeartbeatInterval,omitempty"`

		ID int32 `json:"ID,omitempty"`

		LastSeen *NullTime `json:"LastSeen,omitempty"`

		Name string `json:"Name,omitempty"`

		SecondsSinceSeen int64 `json:"SecondsSinceSeen,omitempty"`

		UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`
	}

	dataAO0.CreatedAt = m.CreatedAt

	dataAO0.HeartbeatInterval = m.HeartbeatInterval

	dataAO0.ID = m.ID

	dataAO0.LastSeen = m.LastSeen

	dataAO0.Name = m.Name

	dataAO0.SecondsSinceSeen = m.SecondsSinceSeen

	dataAO0.UpdatedAt = m.UpdatedAt

	jsonDataAO0, errAO0 := jsonutils.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return jsonutils.ConcatJSON(_parts...), nil
}

// Validate validates this API stale satellite
func (m *APIStaleSatellite) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHeartbeatInterval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSeen(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIStaleSatellite) validateCreatedAt(formats strfmt.Registry) error {

	if typeutils.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("CreatedAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIStaleSatellite) validateHeartbeatInterval(formats strfmt.Registry) error {

	if typeutils.IsZero(m.HeartbeatInterval) { // not required
		return nil
	}

	if m.HeartbeatInterval != nil {
		if err := m.HeartbeatInterval.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("HeartbeatInterval")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("HeartbeatInterval")
			}

			return err
		}
	}

	return nil
}

func (m *APIStaleSatellite) validateLastSeen(formats strfmt.Registry) error {

	if typeutils.IsZero(m.LastSeen) { // not required
		return nil
	}

	if m.LastSeen != nil {
		if err := m.LastSeen.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LastSeen")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LastSeen")
			}

			return err
		}
	}

	return nil
}

func (m *APIStaleSatellite) validateUpdatedAt(formats strfmt.Registry) error {

	if typeutils.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("UpdatedAt", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this API stale satellite based on the context it is used
func (m *APIStaleSatellite) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHeartbeatInterval(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastSeen(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIStaleSatellite) contextValidateHeartbeatInterval(ctx context.Context, formats strfmt.Registry) error {

	if m.HeartbeatInterval != nil {

		if typeutils.IsZero(m.HeartbeatInterval) { // not required
			return nil
		}

		if err := m.HeartbeatInterval.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("HeartbeatInterval")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("HeartbeatInterval")
			}

			return err
		}
	}

	return nil
}

func (m *APIStaleSatellite) contextValidateLastSeen(ctx context.Context, formats strfmt.Registry) error {

	if m.LastSeen != nil {

		if typeutils.IsZero(m.LastSeen) { // not required
			return nil
		}

		if err := m.LastSeen.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LastSeen")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LastSeen")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIStaleSatellite) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIStaleSatellite) UnmarshalBinary(b []byte) error {
	var res APIStaleSatellite
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
