// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APIMessageResponse APIMessageResponse contains a human-readable command result.
//
// swagger:model APIMessageResponse
type APIMessageResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this API message response
func (m *APIMessageResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API message response based on context it is used
func (m *APIMessageResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIMessageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMessageResponse) UnmarshalBinary(b []byte) error {
	var res APIMessageResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
