// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APIHealthResponse APIHealthResponse contains server health status.
//
// swagger:model APIHealthResponse
type APIHealthResponse struct {

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this API health response
func (m *APIHealthResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API health response based on context it is used
func (m *APIHealthResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIHealthResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIHealthResponse) UnmarshalBinary(b []byte) error {
	var res APIHealthResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
