// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// APIGroup APIGroup describes a satellite group row.
//
// swagger:model APIGroup
type APIGroup struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

	// group name
	GroupName string `json:"GroupName,omitempty"`

	// ID
	ID int32 `json:"ID,omitempty"`

	// projects
	Projects []string `json:"Projects"`

	// registry Url
	RegistryURL string `json:"RegistryUrl,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *APIGroup) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

		GroupName string `json:"GroupName,omitempty"`

		ID int32 `json:"ID,omitempty"`

		Projects []string `json:"Projects"`

		RegistryURL string `json:"RegistryUrl,omitempty"`

		UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`
	}
	if err := jsonutils.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.CreatedAt = dataAO0.CreatedAt

	m.GroupName = dataAO0.GroupName

	m.ID = dataAO0.ID

	m.Projects = dataAO0.Projects

	m.RegistryURL = dataAO0.RegistryURL

	m.UpdatedAt = dataAO0.UpdatedAt

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m APIGroup) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

		GroupName string `json:"GroupName,omitempty"`

		ID int32 `json:"ID,omitempty"`

		Projects []string `json:"Projects"`

		RegistryURL string `json:"RegistryUrl,omitempty"`

		UpdatedAt strfmt.DateTime `json:"UpdatedAt,omitempty"`
	}

	dataAO0.CreatedAt = m.CreatedAt

	dataAO0.GroupName = m.GroupName

	dataAO0.ID = m.ID

	dataAO0.Projects = m.Projects

	dataAO0.RegistryURL = m.RegistryURL

	dataAO0.UpdatedAt = m.UpdatedAt

	jsonDataAO0, errAO0 := jsonutils.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return jsonutils.ConcatJSON(_parts...), nil
}

// Validate validates this API group
func (m *APIGroup) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIGroup) validateCreatedAt(formats strfmt.Registry) error {

	if typeutils.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("CreatedAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIGroup) validateUpdatedAt(formats strfmt.Registry) error {

	if typeutils.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("UpdatedAt", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this API group based on context it is used
func (m *APIGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIGroup) UnmarshalBinary(b []byte) error {
	var res APIGroup
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
