// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// APISatelliteStatus APISatelliteStatus describes a stored satellite status report.
//
// swagger:model APISatelliteStatus
type APISatelliteStatus struct {

	// activity
	Activity string `json:"Activity,omitempty"`

	// artifact ids
	ArtifactIds []int32 `json:"ArtifactIds"`

	// Cpu percent
	CPUPercent *NullString `json:"CpuPercent,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

	// ID
	ID int32 `json:"ID,omitempty"`

	// image count
	ImageCount *NullInt32 `json:"ImageCount,omitempty"`

	// last sync duration ms
	LastSyncDurationMs *NullInt64 `json:"LastSyncDurationMs,omitempty"`

	// latest config digest
	LatestConfigDigest *NullString `json:"LatestConfigDigest,omitempty"`

	// latest state digest
	LatestStateDigest *NullString `json:"LatestStateDigest,omitempty"`

	// memory used bytes
	MemoryUsedBytes *NullInt64 `json:"MemoryUsedBytes,omitempty"`

	// reported at
	// Format: date-time
	ReportedAt strfmt.DateTime `json:"ReportedAt,omitempty"`

	// satellite ID
	SatelliteID int32 `json:"SatelliteID,omitempty"`

	// storage used bytes
	StorageUsedBytes *NullInt64 `json:"StorageUsedBytes,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *APISatelliteStatus) UnmarshalJSON(raw []byte) error {
	// AO0
	var dataAO0 struct {
		Activity string `json:"Activity,omitempty"`

		ArtifactIds []int32 `json:"ArtifactIds"`

		CPUPercent *NullString `json:"CpuPercent,omitempty"`

		CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

		ID int32 `json:"ID,omitempty"`

		ImageCount *NullInt32 `json:"ImageCount,omitempty"`

		LastSyncDurationMs *NullInt64 `json:"LastSyncDurationMs,omitempty"`

		LatestConfigDigest *NullString `json:"LatestConfigDigest,omitempty"`

		LatestStateDigest *NullString `json:"LatestStateDigest,omitempty"`

		MemoryUsedBytes *NullInt64 `json:"MemoryUsedBytes,omitempty"`

		ReportedAt strfmt.DateTime `json:"ReportedAt,omitempty"`

		SatelliteID int32 `json:"SatelliteID,omitempty"`

		StorageUsedBytes *NullInt64 `json:"StorageUsedBytes,omitempty"`
	}
	if err := jsonutils.ReadJSON(raw, &dataAO0); err != nil {
		return err
	}

	m.Activity = dataAO0.Activity

	m.ArtifactIds = dataAO0.ArtifactIds

	m.CPUPercent = dataAO0.CPUPercent

	m.CreatedAt = dataAO0.CreatedAt

	m.ID = dataAO0.ID

	m.ImageCount = dataAO0.ImageCount

	m.LastSyncDurationMs = dataAO0.LastSyncDurationMs

	m.LatestConfigDigest = dataAO0.LatestConfigDigest

	m.LatestStateDigest = dataAO0.LatestStateDigest

	m.MemoryUsedBytes = dataAO0.MemoryUsedBytes

	m.ReportedAt = dataAO0.ReportedAt

	m.SatelliteID = dataAO0.SatelliteID

	m.StorageUsedBytes = dataAO0.StorageUsedBytes

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m APISatelliteStatus) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataAO0 struct {
		Activity string `json:"Activity,omitempty"`

		ArtifactIds []int32 `json:"ArtifactIds"`

		CPUPercent *NullString `json:"CpuPercent,omitempty"`

		CreatedAt strfmt.DateTime `json:"CreatedAt,omitempty"`

		ID int32 `json:"ID,omitempty"`

		ImageCount *NullInt32 `json:"ImageCount,omitempty"`

		LastSyncDurationMs *NullInt64 `json:"LastSyncDurationMs,omitempty"`

		LatestConfigDigest *NullString `json:"LatestConfigDigest,omitempty"`

		LatestStateDigest *NullString `json:"LatestStateDigest,omitempty"`

		MemoryUsedBytes *NullInt64 `json:"MemoryUsedBytes,omitempty"`

		ReportedAt strfmt.DateTime `json:"ReportedAt,omitempty"`

		SatelliteID int32 `json:"SatelliteID,omitempty"`

		StorageUsedBytes *NullInt64 `json:"StorageUsedBytes,omitempty"`
	}

	dataAO0.Activity = m.Activity

	dataAO0.ArtifactIds = m.ArtifactIds

	dataAO0.CPUPercent = m.CPUPercent

	dataAO0.CreatedAt = m.CreatedAt

	dataAO0.ID = m.ID

	dataAO0.ImageCount = m.ImageCount

	dataAO0.LastSyncDurationMs = m.LastSyncDurationMs

	dataAO0.LatestConfigDigest = m.LatestConfigDigest

	dataAO0.LatestStateDigest = m.LatestStateDigest

	dataAO0.MemoryUsedBytes = m.MemoryUsedBytes

	dataAO0.ReportedAt = m.ReportedAt

	dataAO0.SatelliteID = m.SatelliteID

	dataAO0.StorageUsedBytes = m.StorageUsedBytes

	jsonDataAO0, errAO0 := jsonutils.WriteJSON(dataAO0)
	if errAO0 != nil {
		return nil, errAO0
	}
	_parts = append(_parts, jsonDataAO0)
	return jsonutils.ConcatJSON(_parts...), nil
}

// Validate validates this API satellite status
func (m *APISatelliteStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCPUPercent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateImageCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastSyncDurationMs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatestConfigDigest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLatestStateDigest(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMemoryUsedBytes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReportedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageUsedBytes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APISatelliteStatus) validateCPUPercent(formats strfmt.Registry) error {

	if typeutils.IsZero(m.CPUPercent) { // not required
		return nil
	}

	if m.CPUPercent != nil {
		if err := m.CPUPercent.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("CpuPercent")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("CpuPercent")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) validateCreatedAt(formats strfmt.Registry) error {

	if typeutils.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("CreatedAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APISatelliteStatus) validateImageCount(formats strfmt.Registry) error {

	if typeutils.IsZero(m.ImageCount) { // not required
		return nil
	}

	if m.ImageCount != nil {
		if err := m.ImageCount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ImageCount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ImageCount")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) validateLastSyncDurationMs(formats strfmt.Registry) error {

	if typeutils.IsZero(m.LastSyncDurationMs) { // not required
		return nil
	}

	if m.LastSyncDurationMs != nil {
		if err := m.LastSyncDurationMs.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LastSyncDurationMs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LastSyncDurationMs")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) validateLatestConfigDigest(formats strfmt.Registry) error {

	if typeutils.IsZero(m.LatestConfigDigest) { // not required
		return nil
	}

	if m.LatestConfigDigest != nil {
		if err := m.LatestConfigDigest.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LatestConfigDigest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LatestConfigDigest")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) validateLatestStateDigest(formats strfmt.Registry) error {

	if typeutils.IsZero(m.LatestStateDigest) { // not required
		return nil
	}

	if m.LatestStateDigest != nil {
		if err := m.LatestStateDigest.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LatestStateDigest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LatestStateDigest")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) validateMemoryUsedBytes(formats strfmt.Registry) error {

	if typeutils.IsZero(m.MemoryUsedBytes) { // not required
		return nil
	}

	if m.MemoryUsedBytes != nil {
		if err := m.MemoryUsedBytes.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("MemoryUsedBytes")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("MemoryUsedBytes")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) validateReportedAt(formats strfmt.Registry) error {

	if typeutils.IsZero(m.ReportedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("ReportedAt", "body", "date-time", m.ReportedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APISatelliteStatus) validateStorageUsedBytes(formats strfmt.Registry) error {

	if typeutils.IsZero(m.StorageUsedBytes) { // not required
		return nil
	}

	if m.StorageUsedBytes != nil {
		if err := m.StorageUsedBytes.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("StorageUsedBytes")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("StorageUsedBytes")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this API satellite status based on the context it is used
func (m *APISatelliteStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCPUPercent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateImageCount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastSyncDurationMs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLatestConfigDigest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLatestStateDigest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMemoryUsedBytes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStorageUsedBytes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APISatelliteStatus) contextValidateCPUPercent(ctx context.Context, formats strfmt.Registry) error {

	if m.CPUPercent != nil {

		if typeutils.IsZero(m.CPUPercent) { // not required
			return nil
		}

		if err := m.CPUPercent.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("CpuPercent")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("CpuPercent")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) contextValidateImageCount(ctx context.Context, formats strfmt.Registry) error {

	if m.ImageCount != nil {

		if typeutils.IsZero(m.ImageCount) { // not required
			return nil
		}

		if err := m.ImageCount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("ImageCount")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("ImageCount")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) contextValidateLastSyncDurationMs(ctx context.Context, formats strfmt.Registry) error {

	if m.LastSyncDurationMs != nil {

		if typeutils.IsZero(m.LastSyncDurationMs) { // not required
			return nil
		}

		if err := m.LastSyncDurationMs.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LastSyncDurationMs")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LastSyncDurationMs")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) contextValidateLatestConfigDigest(ctx context.Context, formats strfmt.Registry) error {

	if m.LatestConfigDigest != nil {

		if typeutils.IsZero(m.LatestConfigDigest) { // not required
			return nil
		}

		if err := m.LatestConfigDigest.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LatestConfigDigest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LatestConfigDigest")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) contextValidateLatestStateDigest(ctx context.Context, formats strfmt.Registry) error {

	if m.LatestStateDigest != nil {

		if typeutils.IsZero(m.LatestStateDigest) { // not required
			return nil
		}

		if err := m.LatestStateDigest.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("LatestStateDigest")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("LatestStateDigest")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) contextValidateMemoryUsedBytes(ctx context.Context, formats strfmt.Registry) error {

	if m.MemoryUsedBytes != nil {

		if typeutils.IsZero(m.MemoryUsedBytes) { // not required
			return nil
		}

		if err := m.MemoryUsedBytes.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("MemoryUsedBytes")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("MemoryUsedBytes")
			}

			return err
		}
	}

	return nil
}

func (m *APISatelliteStatus) contextValidateStorageUsedBytes(ctx context.Context, formats strfmt.Registry) error {

	if m.StorageUsedBytes != nil {

		if typeutils.IsZero(m.StorageUsedBytes) { // not required
			return nil
		}

		if err := m.StorageUsedBytes.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("StorageUsedBytes")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("StorageUsedBytes")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APISatelliteStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APISatelliteStatus) UnmarshalBinary(b []byte) error {
	var res APISatelliteStatus
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
