// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// CachedImage CachedImage describes an image cached by a satellite.
//
// swagger:model CachedImage
type CachedImage struct {

	// reference
	Reference string `json:"reference,omitempty"`

	// size bytes
	SizeBytes int64 `json:"size_bytes,omitempty"`
}

// Validate validates this cached image
func (m *CachedImage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cached image based on context it is used
func (m *CachedImage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CachedImage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CachedImage) UnmarshalBinary(b []byte) error {
	var res CachedImage
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
