// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// ChangePasswordRequest ChangePasswordRequest changes the authenticated user's password.
//
// swagger:model changePasswordRequest
type ChangePasswordRequest struct {

	// current password
	// Required: true
	// Format: password
	CurrentPassword *strfmt.Password `json:"current_password"`

	// new password
	// Required: true
	// Format: password
	NewPassword *strfmt.Password `json:"new_password"`
}

// Validate validates this change password request
func (m *ChangePasswordRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCurrentPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChangePasswordRequest) validateCurrentPassword(formats strfmt.Registry) error {

	if err := validate.Required("current_password", "body", m.CurrentPassword); err != nil {
		return err
	}

	if err := validate.FormatOf("current_password", "body", "password", m.CurrentPassword.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ChangePasswordRequest) validateNewPassword(formats strfmt.Registry) error {

	if err := validate.Required("new_password", "body", m.NewPassword); err != nil {
		return err
	}

	if err := validate.FormatOf("new_password", "body", "password", m.NewPassword.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this change password request based on context it is used
func (m *ChangePasswordRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangePasswordRequest) UnmarshalBinary(b []byte) error {
	var res ChangePasswordRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
