// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// NullInt32 NullInt32 represents an int32 that may be null.
//
// NullInt32 implements the [Scanner] interface so
// it can be used as a scan destination, similar to [NullString].
//
// swagger:model NullInt32
type NullInt32 struct {

	// int32
	Int32 int32 `json:"Int32,omitempty"`

	// valid
	Valid bool `json:"Valid,omitempty"`
}

// Validate validates this null int32
func (m *NullInt32) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this null int32 based on context it is used
func (m *NullInt32) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NullInt32) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NullInt32) UnmarshalBinary(b []byte) error {
	var res NullInt32
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
