// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RegisterSatelliteParams RegisterSatelliteParams registers a token-managed satellite.
//
// swagger:model RegisterSatelliteParams
type RegisterSatelliteParams struct {

	// config name
	ConfigName string `json:"config_name,omitempty"`

	// groups
	Groups []string `json:"groups"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this register satellite params
func (m *RegisterSatelliteParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this register satellite params based on context it is used
func (m *RegisterSatelliteParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterSatelliteParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterSatelliteParams) UnmarshalBinary(b []byte) error {
	var res RegisterSatelliteParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
