// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// RegisterSatelliteRequest RegisterSatelliteRequest represents a request to register a satellite with SPIFFE.
//
// swagger:model RegisterSatelliteRequest
type RegisterSatelliteRequest struct {

	// attestation method
	// Required: true
	// Enum: ["join_token","x509pop","sshpop"]
	AttestationMethod *string `json:"attestation_method"`

	// parent agent ID
	ParentAgentID string `json:"parent_agent_id,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// satellite name
	// Required: true
	SatelliteName *string `json:"satellite_name"`

	// selectors
	// Required: true
	// Min Items: 1
	Selectors []string `json:"selectors"`

	// TTL seconds
	// Maximum: 86400
	// Minimum: 1
	TTLSeconds int64 `json:"ttl_seconds,omitempty"`
}

// Validate validates this register satellite request
func (m *RegisterSatelliteRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttestationMethod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSatelliteName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelectors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTTLSeconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var registerSatelliteRequestTypeAttestationMethodPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["join_token","x509pop","sshpop"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		registerSatelliteRequestTypeAttestationMethodPropEnum = append(registerSatelliteRequestTypeAttestationMethodPropEnum, v)
	}
}

const (

	// RegisterSatelliteRequestAttestationMethodJoinToken captures enum value "join_token"
	RegisterSatelliteRequestAttestationMethodJoinToken string = "join_token"

	// RegisterSatelliteRequestAttestationMethodX509pop captures enum value "x509pop"
	RegisterSatelliteRequestAttestationMethodX509pop string = "x509pop"

	// RegisterSatelliteRequestAttestationMethodSshpop captures enum value "sshpop"
	RegisterSatelliteRequestAttestationMethodSshpop string = "sshpop"
)

// prop value enum
func (m *RegisterSatelliteRequest) validateAttestationMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, registerSatelliteRequestTypeAttestationMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RegisterSatelliteRequest) validateAttestationMethod(formats strfmt.Registry) error {

	if err := validate.Required("attestation_method", "body", m.AttestationMethod); err != nil {
		return err
	}

	// value enum
	if err := m.validateAttestationMethodEnum("attestation_method", "body", *m.AttestationMethod); err != nil {
		return err
	}

	return nil
}

func (m *RegisterSatelliteRequest) validateSatelliteName(formats strfmt.Registry) error {

	if err := validate.Required("satellite_name", "body", m.SatelliteName); err != nil {
		return err
	}

	return nil
}

func (m *RegisterSatelliteRequest) validateSelectors(formats strfmt.Registry) error {

	if err := validate.Required("selectors", "body", m.Selectors); err != nil {
		return err
	}

	iSelectorsSize := int64(len(m.Selectors))

	if err := validate.MinItems("selectors", "body", iSelectorsSize, 1); err != nil {
		return err
	}

	return nil
}

func (m *RegisterSatelliteRequest) validateTTLSeconds(formats strfmt.Registry) error {
	if typeutils.IsZero(m.TTLSeconds) { // not required
		return nil
	}

	if err := validate.MinimumInt("ttl_seconds", "body", m.TTLSeconds, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("ttl_seconds", "body", m.TTLSeconds, 86400, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this register satellite request based on context it is used
func (m *RegisterSatelliteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterSatelliteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterSatelliteRequest) UnmarshalBinary(b []byte) error {
	var res RegisterSatelliteRequest
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
