// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RegisterSatelliteResponse RegisterSatelliteResponse contains a single-use ZTR token.
//
// swagger:model RegisterSatelliteResponse
type RegisterSatelliteResponse struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this register satellite response
func (m *RegisterSatelliteResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this register satellite response based on context it is used
func (m *RegisterSatelliteResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterSatelliteResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterSatelliteResponse) UnmarshalBinary(b []byte) error {
	var res RegisterSatelliteResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
