// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// RegisterSatelliteWithSPIFFEResponse RegisterSatelliteWithSPIFFEResponse contains satellite registration details.
//
// swagger:model RegisterSatelliteWithSPIFFEResponse
type RegisterSatelliteWithSPIFFEResponse struct {

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires_at,omitempty"`

	// join token
	JoinToken string `json:"join_token,omitempty"`

	// parent agent ID
	ParentAgentID string `json:"parent_agent_id,omitempty"`

	// region
	Region string `json:"region,omitempty"`

	// satellite
	Satellite string `json:"satellite,omitempty"`

	// spiffe ID
	SpiffeID string `json:"spiffe_id,omitempty"`

	// spire server address
	SpireServerAddress string `json:"spire_server_address,omitempty"`

	// spire server port
	SpireServerPort int64 `json:"spire_server_port,omitempty"`

	// trust domain
	TrustDomain string `json:"trust_domain,omitempty"`
}

// Validate validates this register satellite with s p i f f e response
func (m *RegisterSatelliteWithSPIFFEResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterSatelliteWithSPIFFEResponse) validateExpiresAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires_at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this register satellite with s p i f f e response based on context it is used
func (m *RegisterSatelliteWithSPIFFEResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterSatelliteWithSPIFFEResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterSatelliteWithSPIFFEResponse) UnmarshalBinary(b []byte) error {
	var res RegisterSatelliteWithSPIFFEResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
