// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SPIREStatusResponse SPIREStatusResponse contains SPIRE integration status.
//
// swagger:model SPIREStatusResponse
type SPIREStatusResponse struct {

	// connected
	Connected bool `json:"connected,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// provider
	Provider string `json:"provider,omitempty"`

	// trust domain
	TrustDomain string `json:"trust_domain,omitempty"`
}

// Validate validates this s p i r e status response
func (m *SPIREStatusResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this s p i r e status response based on context it is used
func (m *SPIREStatusResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SPIREStatusResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SPIREStatusResponse) UnmarshalBinary(b []byte) error {
	var res SPIREStatusResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
