// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SatelliteConfigParams SatelliteConfigParams links a satellite to a named configuration.
//
// swagger:model SatelliteConfigParams
type SatelliteConfigParams struct {

	// config name
	ConfigName string `json:"config_name,omitempty"`

	// satellite
	Satellite string `json:"satellite,omitempty"`
}

// Validate validates this satellite config params
func (m *SatelliteConfigParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this satellite config params based on context it is used
func (m *SatelliteConfigParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SatelliteConfigParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SatelliteConfigParams) UnmarshalBinary(b []byte) error {
	var res SatelliteConfigParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
