// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// SatelliteStatusParams SatelliteStatusParams reports the current satellite status and cache metrics.
//
// swagger:model SatelliteStatusParams
type SatelliteStatusParams struct {

	// activity
	Activity string `json:"activity,omitempty"`

	// CPU percent
	CPUPercent float64 `json:"cpu_percent,omitempty"`

	// cached images
	CachedImages []*CachedImage `json:"cached_images"`

	// image count
	ImageCount int64 `json:"image_count,omitempty"`

	// last sync duration ms
	LastSyncDurationMs int64 `json:"last_sync_duration_ms,omitempty"`

	// latest config digest
	LatestConfigDigest string `json:"latest_config_digest,omitempty"`

	// latest state digest
	LatestStateDigest string `json:"latest_state_digest,omitempty"`

	// memory used bytes
	MemoryUsedBytes uint64 `json:"memory_used_bytes,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// request created time
	// Format: date-time
	RequestCreatedTime strfmt.DateTime `json:"request_created_time,omitempty"`

	// state report interval
	StateReportInterval string `json:"state_report_interval,omitempty"`

	// storage used bytes
	StorageUsedBytes uint64 `json:"storage_used_bytes,omitempty"`
}

// Validate validates this satellite status params
func (m *SatelliteStatusParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCachedImages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestCreatedTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SatelliteStatusParams) validateCachedImages(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CachedImages) { // not required
		return nil
	}

	for i := 0; i < len(m.CachedImages); i++ {
		if typeutils.IsZero(m.CachedImages[i]) { // not required
			continue
		}

		if m.CachedImages[i] != nil {
			if err := m.CachedImages[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("cached_images" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("cached_images" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *SatelliteStatusParams) validateRequestCreatedTime(formats strfmt.Registry) error {
	if typeutils.IsZero(m.RequestCreatedTime) { // not required
		return nil
	}

	if err := validate.FormatOf("request_created_time", "body", "date-time", m.RequestCreatedTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this satellite status params based on the context it is used
func (m *SatelliteStatusParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCachedImages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SatelliteStatusParams) contextValidateCachedImages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CachedImages); i++ {

		if m.CachedImages[i] != nil {

			if typeutils.IsZero(m.CachedImages[i]) { // not required
				return nil
			}

			if err := m.CachedImages[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("cached_images" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("cached_images" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SatelliteStatusParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SatelliteStatusParams) UnmarshalBinary(b []byte) error {
	var res SatelliteStatusParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
