// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SatelliteGroupParams SatelliteGroupParams links or unlinks a satellite and a group.
//
// swagger:model SatelliteGroupParams
type SatelliteGroupParams struct {

	// group
	Group string `json:"group,omitempty"`

	// satellite
	Satellite string `json:"satellite,omitempty"`
}

// Validate validates this satellite group params
func (m *SatelliteGroupParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this satellite group params based on context it is used
func (m *SatelliteGroupParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SatelliteGroupParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SatelliteGroupParams) UnmarshalBinary(b []byte) error {
	var res SatelliteGroupParams
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
