// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// UserResponse UserResponse describes a Ground Control user.
//
// swagger:model userResponse
type UserResponse struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// ID
	ID int32 `json:"id,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this user response
func (m *UserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user response based on context it is used
func (m *UserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserResponse) UnmarshalBinary(b []byte) error {
	var res UserResponse
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
