// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSpireStatusHandlerFunc turns a function with the right signature into a get spire status handler
type GetSpireStatusHandlerFunc func(GetSpireStatusParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSpireStatusHandlerFunc) Handle(params GetSpireStatusParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// GetSpireStatusHandler interface for that can handle valid get spire status params
type GetSpireStatusHandler interface {
	Handle(GetSpireStatusParams, any) middleware.Responder
}

// NewGetSpireStatus creates a new http.Handler for the get spire status operation
func NewGetSpireStatus(ctx *middleware.Context, handler GetSpireStatusHandler) *GetSpireStatus {
	return &GetSpireStatus{Context: ctx, Handler: handler}
}

// GetSpireStatus swagger:route GET /api/spire/status spire getSpireStatus
//
// Gets SPIRE integration status.
type GetSpireStatus struct {
	Context *middleware.Context
	Handler GetSpireStatusHandler
}

func (o *GetSpireStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewGetSpireStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
