// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// GetSpireStatusOKCode is the HTTP code returned for type GetSpireStatusOK
const GetSpireStatusOKCode int = 200

// GetSpireStatusOK SPIRE integration status returned.
//
// swagger:response getSpireStatusOK
type GetSpireStatusOK struct {

	// In: Body
	Payload *models.SPIREStatusResponse `json:"body,omitempty"`
}

// NewGetSpireStatusOK creates GetSpireStatusOK with default headers values
func NewGetSpireStatusOK() *GetSpireStatusOK {

	return &GetSpireStatusOK{}
}

// WithPayload adds the payload to the get spire status o k response
func (o *GetSpireStatusOK) WithPayload(payload *models.SPIREStatusResponse) *GetSpireStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get spire status o k response
func (o *GetSpireStatusOK) SetPayload(payload *models.SPIREStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSpireStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSpireStatusUnauthorizedCode is the HTTP code returned for type GetSpireStatusUnauthorized
const GetSpireStatusUnauthorizedCode int = 401

// GetSpireStatusUnauthorized Authorization token is missing or invalid.
//
// swagger:response getSpireStatusUnauthorized
type GetSpireStatusUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSpireStatusUnauthorized creates GetSpireStatusUnauthorized with default headers values
func NewGetSpireStatusUnauthorized() *GetSpireStatusUnauthorized {

	return &GetSpireStatusUnauthorized{}
}

// WithPayload adds the payload to the get spire status unauthorized response
func (o *GetSpireStatusUnauthorized) WithPayload(payload *models.AppError) *GetSpireStatusUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get spire status unauthorized response
func (o *GetSpireStatusUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSpireStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSpireStatusForbiddenCode is the HTTP code returned for type GetSpireStatusForbidden
const GetSpireStatusForbiddenCode int = 403

// GetSpireStatusForbidden System administrator role is required.
//
// swagger:response getSpireStatusForbidden
type GetSpireStatusForbidden struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewGetSpireStatusForbidden creates GetSpireStatusForbidden with default headers values
func NewGetSpireStatusForbidden() *GetSpireStatusForbidden {

	return &GetSpireStatusForbidden{}
}

// WithPayload adds the payload to the get spire status forbidden response
func (o *GetSpireStatusForbidden) WithPayload(payload *models.AppError) *GetSpireStatusForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get spire status forbidden response
func (o *GetSpireStatusForbidden) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSpireStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
