// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetSpireStatusParams creates a new GetSpireStatusParams object
//
// There are no default values defined in the spec.
func NewGetSpireStatusParams() GetSpireStatusParams {

	return GetSpireStatusParams{}
}

// GetSpireStatusParams contains all the bound params for the get spire status operation
// typically these are obtained from a http.Request
//
// swagger:parameters getSpireStatus
type GetSpireStatusParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSpireStatusParams() beforehand.
func (o *GetSpireStatusParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
