// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewListSpireAgentsParams creates a new ListSpireAgentsParams object
//
// There are no default values defined in the spec.
func NewListSpireAgentsParams() ListSpireAgentsParams {

	return ListSpireAgentsParams{}
}

// ListSpireAgentsParams contains all the bound params for the list spire agents operation
// typically these are obtained from a http.Request
//
// swagger:parameters listSpireAgents
type ListSpireAgentsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
	// Filters agents by attestation type.
	// In: query
	AttestationType *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListSpireAgentsParams() beforehand.
func (o *ListSpireAgentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qAttestationType, qhkAttestationType, _ := qs.GetOK("attestation_type")
	if err := o.bindAttestationType(qAttestationType, qhkAttestationType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAttestationType binds and validates parameter AttestationType from query.
func (o *ListSpireAgentsParams) bindAttestationType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.AttestationType = &raw

	return nil
}
