// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// ListSpireAgentsOKCode is the HTTP code returned for type ListSpireAgentsOK
const ListSpireAgentsOKCode int = 200

// ListSpireAgentsOK SPIRE agents returned.
//
// swagger:response listSpireAgentsOK
type ListSpireAgentsOK struct {

	// In: Body
	Payload *models.AgentListResponse `json:"body,omitempty"`
}

// NewListSpireAgentsOK creates ListSpireAgentsOK with default headers values
func NewListSpireAgentsOK() *ListSpireAgentsOK {

	return &ListSpireAgentsOK{}
}

// WithPayload adds the payload to the list spire agents o k response
func (o *ListSpireAgentsOK) WithPayload(payload *models.AgentListResponse) *ListSpireAgentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list spire agents o k response
func (o *ListSpireAgentsOK) SetPayload(payload *models.AgentListResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSpireAgentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSpireAgentsUnauthorizedCode is the HTTP code returned for type ListSpireAgentsUnauthorized
const ListSpireAgentsUnauthorizedCode int = 401

// ListSpireAgentsUnauthorized Authorization token is missing or invalid.
//
// swagger:response listSpireAgentsUnauthorized
type ListSpireAgentsUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListSpireAgentsUnauthorized creates ListSpireAgentsUnauthorized with default headers values
func NewListSpireAgentsUnauthorized() *ListSpireAgentsUnauthorized {

	return &ListSpireAgentsUnauthorized{}
}

// WithPayload adds the payload to the list spire agents unauthorized response
func (o *ListSpireAgentsUnauthorized) WithPayload(payload *models.AppError) *ListSpireAgentsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list spire agents unauthorized response
func (o *ListSpireAgentsUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSpireAgentsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSpireAgentsForbiddenCode is the HTTP code returned for type ListSpireAgentsForbidden
const ListSpireAgentsForbiddenCode int = 403

// ListSpireAgentsForbidden System administrator role is required.
//
// swagger:response listSpireAgentsForbidden
type ListSpireAgentsForbidden struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListSpireAgentsForbidden creates ListSpireAgentsForbidden with default headers values
func NewListSpireAgentsForbidden() *ListSpireAgentsForbidden {

	return &ListSpireAgentsForbidden{}
}

// WithPayload adds the payload to the list spire agents forbidden response
func (o *ListSpireAgentsForbidden) WithPayload(payload *models.AppError) *ListSpireAgentsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list spire agents forbidden response
func (o *ListSpireAgentsForbidden) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSpireAgentsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSpireAgentsInternalServerErrorCode is the HTTP code returned for type ListSpireAgentsInternalServerError
const ListSpireAgentsInternalServerErrorCode int = 500

// ListSpireAgentsInternalServerError SPIRE agents could not be listed.
//
// swagger:response listSpireAgentsInternalServerError
type ListSpireAgentsInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListSpireAgentsInternalServerError creates ListSpireAgentsInternalServerError with default headers values
func NewListSpireAgentsInternalServerError() *ListSpireAgentsInternalServerError {

	return &ListSpireAgentsInternalServerError{}
}

// WithPayload adds the payload to the list spire agents internal server error response
func (o *ListSpireAgentsInternalServerError) WithPayload(payload *models.AppError) *ListSpireAgentsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list spire agents internal server error response
func (o *ListSpireAgentsInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSpireAgentsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListSpireAgentsServiceUnavailableCode is the HTTP code returned for type ListSpireAgentsServiceUnavailable
const ListSpireAgentsServiceUnavailableCode int = 503

// ListSpireAgentsServiceUnavailable SPIRE server is not configured.
//
// swagger:response listSpireAgentsServiceUnavailable
type ListSpireAgentsServiceUnavailable struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewListSpireAgentsServiceUnavailable creates ListSpireAgentsServiceUnavailable with default headers values
func NewListSpireAgentsServiceUnavailable() *ListSpireAgentsServiceUnavailable {

	return &ListSpireAgentsServiceUnavailable{}
}

// WithPayload adds the payload to the list spire agents service unavailable response
func (o *ListSpireAgentsServiceUnavailable) WithPayload(payload *models.AppError) *ListSpireAgentsServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list spire agents service unavailable response
func (o *ListSpireAgentsServiceUnavailable) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSpireAgentsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
