// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListSpireAgentsHandlerFunc turns a function with the right signature into a list spire agents handler
type ListSpireAgentsHandlerFunc func(ListSpireAgentsParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn ListSpireAgentsHandlerFunc) Handle(params ListSpireAgentsParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// ListSpireAgentsHandler interface for that can handle valid list spire agents params
type ListSpireAgentsHandler interface {
	Handle(ListSpireAgentsParams, any) middleware.Responder
}

// NewListSpireAgents creates a new http.Handler for the list spire agents operation
func NewListSpireAgents(ctx *middleware.Context, handler ListSpireAgentsHandler) *ListSpireAgents {
	return &ListSpireAgents{Context: ctx, Handler: handler}
}

// ListSpireAgents swagger:route GET /api/spire/agents spire listSpireAgents
//
// Lists attested SPIRE agents.
type ListSpireAgents struct {
	Context *middleware.Context
	Handler ListSpireAgentsHandler
}

func (o *ListSpireAgents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewListSpireAgentsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
