// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RegisterSatelliteWithSpiffeHandlerFunc turns a function with the right signature into a register satellite with spiffe handler
type RegisterSatelliteWithSpiffeHandlerFunc func(RegisterSatelliteWithSpiffeParams, any) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterSatelliteWithSpiffeHandlerFunc) Handle(params RegisterSatelliteWithSpiffeParams, principal any) middleware.Responder {
	return fn(params, principal)
}

// RegisterSatelliteWithSpiffeHandler interface for that can handle valid register satellite with spiffe params
type RegisterSatelliteWithSpiffeHandler interface {
	Handle(RegisterSatelliteWithSpiffeParams, any) middleware.Responder
}

// NewRegisterSatelliteWithSpiffe creates a new http.Handler for the register satellite with spiffe operation
func NewRegisterSatelliteWithSpiffe(ctx *middleware.Context, handler RegisterSatelliteWithSpiffeHandler) *RegisterSatelliteWithSpiffe {
	return &RegisterSatelliteWithSpiffe{Context: ctx, Handler: handler}
}

// RegisterSatelliteWithSpiffe swagger:route POST /api/satellites/register spire registerSatelliteWithSpiffe
//
// Registers a satellite workload identity with SPIFFE.
type RegisterSatelliteWithSpiffe struct {
	Context *middleware.Context
	Handler RegisterSatelliteWithSpiffeHandler
}

func (o *RegisterSatelliteWithSpiffe) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	params := NewRegisterSatelliteWithSpiffeParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal any
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
