// Code generated by go-swagger; DO NOT EDIT.

package spire

import (
	"net/http"

	"github.com/container-registry/harbor-satellite/internal/groundcontrol/swagger/models"
	"github.com/go-openapi/runtime"
)

// RegisterSatelliteWithSpiffeOKCode is the HTTP code returned for type RegisterSatelliteWithSpiffeOK
const RegisterSatelliteWithSpiffeOKCode int = 200

// RegisterSatelliteWithSpiffeOK SPIFFE workload identity registered.
//
// swagger:response registerSatelliteWithSpiffeOK
type RegisterSatelliteWithSpiffeOK struct {

	// In: Body
	Payload *models.RegisterSatelliteWithSPIFFEResponse `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeOK creates RegisterSatelliteWithSpiffeOK with default headers values
func NewRegisterSatelliteWithSpiffeOK() *RegisterSatelliteWithSpiffeOK {

	return &RegisterSatelliteWithSpiffeOK{}
}

// WithPayload adds the payload to the register satellite with spiffe o k response
func (o *RegisterSatelliteWithSpiffeOK) WithPayload(payload *models.RegisterSatelliteWithSPIFFEResponse) *RegisterSatelliteWithSpiffeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe o k response
func (o *RegisterSatelliteWithSpiffeOK) SetPayload(payload *models.RegisterSatelliteWithSPIFFEResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteWithSpiffeBadRequestCode is the HTTP code returned for type RegisterSatelliteWithSpiffeBadRequest
const RegisterSatelliteWithSpiffeBadRequestCode int = 400

// RegisterSatelliteWithSpiffeBadRequest Registration payload, selectors, or attestation method is invalid.
//
// swagger:response registerSatelliteWithSpiffeBadRequest
type RegisterSatelliteWithSpiffeBadRequest struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeBadRequest creates RegisterSatelliteWithSpiffeBadRequest with default headers values
func NewRegisterSatelliteWithSpiffeBadRequest() *RegisterSatelliteWithSpiffeBadRequest {

	return &RegisterSatelliteWithSpiffeBadRequest{}
}

// WithPayload adds the payload to the register satellite with spiffe bad request response
func (o *RegisterSatelliteWithSpiffeBadRequest) WithPayload(payload *models.AppError) *RegisterSatelliteWithSpiffeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe bad request response
func (o *RegisterSatelliteWithSpiffeBadRequest) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteWithSpiffeUnauthorizedCode is the HTTP code returned for type RegisterSatelliteWithSpiffeUnauthorized
const RegisterSatelliteWithSpiffeUnauthorizedCode int = 401

// RegisterSatelliteWithSpiffeUnauthorized Authorization token is missing or invalid.
//
// swagger:response registerSatelliteWithSpiffeUnauthorized
type RegisterSatelliteWithSpiffeUnauthorized struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeUnauthorized creates RegisterSatelliteWithSpiffeUnauthorized with default headers values
func NewRegisterSatelliteWithSpiffeUnauthorized() *RegisterSatelliteWithSpiffeUnauthorized {

	return &RegisterSatelliteWithSpiffeUnauthorized{}
}

// WithPayload adds the payload to the register satellite with spiffe unauthorized response
func (o *RegisterSatelliteWithSpiffeUnauthorized) WithPayload(payload *models.AppError) *RegisterSatelliteWithSpiffeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe unauthorized response
func (o *RegisterSatelliteWithSpiffeUnauthorized) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteWithSpiffeForbiddenCode is the HTTP code returned for type RegisterSatelliteWithSpiffeForbidden
const RegisterSatelliteWithSpiffeForbiddenCode int = 403

// RegisterSatelliteWithSpiffeForbidden System administrator role is required.
//
// swagger:response registerSatelliteWithSpiffeForbidden
type RegisterSatelliteWithSpiffeForbidden struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeForbidden creates RegisterSatelliteWithSpiffeForbidden with default headers values
func NewRegisterSatelliteWithSpiffeForbidden() *RegisterSatelliteWithSpiffeForbidden {

	return &RegisterSatelliteWithSpiffeForbidden{}
}

// WithPayload adds the payload to the register satellite with spiffe forbidden response
func (o *RegisterSatelliteWithSpiffeForbidden) WithPayload(payload *models.AppError) *RegisterSatelliteWithSpiffeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe forbidden response
func (o *RegisterSatelliteWithSpiffeForbidden) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteWithSpiffeNotFoundCode is the HTTP code returned for type RegisterSatelliteWithSpiffeNotFound
const RegisterSatelliteWithSpiffeNotFoundCode int = 404

// RegisterSatelliteWithSpiffeNotFound Required parent agent was not found.
//
// swagger:response registerSatelliteWithSpiffeNotFound
type RegisterSatelliteWithSpiffeNotFound struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeNotFound creates RegisterSatelliteWithSpiffeNotFound with default headers values
func NewRegisterSatelliteWithSpiffeNotFound() *RegisterSatelliteWithSpiffeNotFound {

	return &RegisterSatelliteWithSpiffeNotFound{}
}

// WithPayload adds the payload to the register satellite with spiffe not found response
func (o *RegisterSatelliteWithSpiffeNotFound) WithPayload(payload *models.AppError) *RegisterSatelliteWithSpiffeNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe not found response
func (o *RegisterSatelliteWithSpiffeNotFound) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteWithSpiffeInternalServerErrorCode is the HTTP code returned for type RegisterSatelliteWithSpiffeInternalServerError
const RegisterSatelliteWithSpiffeInternalServerErrorCode int = 500

// RegisterSatelliteWithSpiffeInternalServerError SPIFFE registration could not be completed.
//
// swagger:response registerSatelliteWithSpiffeInternalServerError
type RegisterSatelliteWithSpiffeInternalServerError struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeInternalServerError creates RegisterSatelliteWithSpiffeInternalServerError with default headers values
func NewRegisterSatelliteWithSpiffeInternalServerError() *RegisterSatelliteWithSpiffeInternalServerError {

	return &RegisterSatelliteWithSpiffeInternalServerError{}
}

// WithPayload adds the payload to the register satellite with spiffe internal server error response
func (o *RegisterSatelliteWithSpiffeInternalServerError) WithPayload(payload *models.AppError) *RegisterSatelliteWithSpiffeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe internal server error response
func (o *RegisterSatelliteWithSpiffeInternalServerError) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterSatelliteWithSpiffeServiceUnavailableCode is the HTTP code returned for type RegisterSatelliteWithSpiffeServiceUnavailable
const RegisterSatelliteWithSpiffeServiceUnavailableCode int = 503

// RegisterSatelliteWithSpiffeServiceUnavailable SPIRE server is not configured.
//
// swagger:response registerSatelliteWithSpiffeServiceUnavailable
type RegisterSatelliteWithSpiffeServiceUnavailable struct {

	// In: Body
	Payload *models.AppError `json:"body,omitempty"`
}

// NewRegisterSatelliteWithSpiffeServiceUnavailable creates RegisterSatelliteWithSpiffeServiceUnavailable with default headers values
func NewRegisterSatelliteWithSpiffeServiceUnavailable() *RegisterSatelliteWithSpiffeServiceUnavailable {

	return &RegisterSatelliteWithSpiffeServiceUnavailable{}
}

// WithPayload adds the payload to the register satellite with spiffe service unavailable response
func (o *RegisterSatelliteWithSpiffeServiceUnavailable) WithPayload(payload *models.AppError) *RegisterSatelliteWithSpiffeServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register satellite with spiffe service unavailable response
func (o *RegisterSatelliteWithSpiffeServiceUnavailable) SetPayload(payload *models.AppError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterSatelliteWithSpiffeServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
