name: Build
on:
  # Build only triggers once lint and test workflow successfully completes
  workflow_run:
    workflows: [Lint]
    types:
      - completed

jobs:
  dagger-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout repository
      uses: actions/checkout@v4
    - 
      name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.20'
    -
        name: Install
        run: go get dagger.io/dagger@latest
    -
        name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sh; cd -; }
    -
        name: Build with Dagger
        run: dagger run go run ci/main.go
    
