name: Main and Release Pipeline

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "*.md"
      - "assets/**"

jobs:
  push-latest-images:
    permissions:
      contents: read
      id-token: write
    runs-on: container-registry
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Print GitHub ref for debugging
        run: |
          echo "GitHub ref: $GITHUB_REF"

      - name: Checkout repo
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Publish and Sign Snapshot Image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
        uses: ./.github/actions/publish-and-sign
        with:
          IMAGE_TAGS: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_ADDRESS: ${{ vars.REGISTRY_ADDRESS }}
          REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}

  publish-release:
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: container-registry
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Checkout repo
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Publish and Sign Tagged Image
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: ./.github/actions/publish-and-sign
        with:
          IMAGE_TAGS: "latest,${{ github.ref_name }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_ADDRESS: ${{ vars.REGISTRY_ADDRESS }}
          REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}

      - name: Setup Go
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.26.2"

      - name: Install Task
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x

      - name: Install GoReleaser
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          install-only: true
          version: v2.9.0

      - name: Install Syft
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        uses: anchore/sbom-action/download-syft@28d71544de8eaf1b958d335707167c5f783590ad # v0.22.2

      - name: Create Release
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: task release
